In [ ]:
# Introduction to Pandas

# Pandas
# Pandas is an important library for data manipulation, wrangling, and analysis.
# What is Data Manipulation?
# Eg: If we had a price column in a dataset, we might want to manipulate the data by converting the prices from one currency to another. 
# This is an example of data manipulation.
# What is Data Wrangling?
# Data wrangling is the process of cleaning and transforming raw data into a format that is suitable for analysis. This can involve tasks such as handling missing values, 
# removing duplicates, and converting data types.
# Eg: If we had a price column in a dataset with values in different formats (e.g., "$10", "10 USD", "10"), we might want to wrangle the data by standardizing the format 
# of the prices. This is an example of data wrangling.
# Eg: If we had a price column in a dataset with some missing values, we might want to wrangle the data by filling in the missing values with the average price.
# This is another example of data wrangling.
# What is Data Analysis?
# Data analysis is the process of examining, cleaning, transforming, and modeling data to discover useful information, draw conclusions, and support decision-making.
# Eg: If we had a price column in a dataset, we might want to analyze the data by calculating the average price, finding the maximum and minimum prices, 
# and identifying any trends or patterns in the data. This is an example of data analysis.

# Pandas: Pan - Panel Data, das - Data Analysis System
# It is built on top of NumPy and is designed to work seamlessly with it.
# It is also the most widely used library for data analysis in Python.
# It is used in a variety of fields, including finance, economics, statistics, and data science.
# It is also used in machine learning and deep learning.

# Data Structures of Pandas
# Pandas provides two main data structures: Series and DataFrame.
# 1. Series:
#    - A one-dimensional labeled array capable of holding any data type.
#    - It is similar to a list or a dictionary, but it has an index that allows for easy access to the data.
#    - It can be created from a list, dictionary, or NumPy array.
# 2. DataFrame:
#    - A two-dimensional labeled data structure with columns of potentially different types.
#    - It is similar to a spreadsheet or SQL table, or a dictionary of Series objects.
#    - It can be created from a dictionary of Series, a list of dictionaries, or a NumPy array.
#    - It is the most commonly used data structure in Pandas and is used for most data analysis tasks.
#    - It is also the most powerful data structure in Pandas and is used for most data manipulation tasks.
#    - It is used for data wrangling, data cleaning, and data analysis.
#    - It is used for data visualization and data exploration.
#    - It is used for data preprocessing and feature engineering.
#    - It is used for data modeling and machine learning.
#    - It is used for data storage and data retrieval.
#    - It is used for data transformation and data aggregation.
#    - It is used for data merging and data joining.
#    - It is used for data reshaping and data pivoting.
#    - It is used for data filtering and data selection.
#    - It is used for data grouping and data aggregation.
#    - It is used for data sorting and data ordering.
#    - It is used for data indexing and data slicing.
#    - It is used for data concatenation and data appending.
#    - It is used for data splitting and data merging.
#    - It is used for data reshaping and data pivoting.
#    - It is used for data filtering and data selection.

In [2]:
!pip install pandas
import pandas as pd
print(pd.__version__) # Version of Pandas

# Note:
# Your version of Pandas may be different from the one shown in the output above, as it depends on the version you have installed in your environment.
# However, the concepts and functionalities of Pandas remain consistent across different versions, so you can still follow along with the examples and explanations provided in this introduction to Pandas.
# I can almost guarantee this notebook will work with any version of Pandas.

[notice] A new release of pip is available: 23.2.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\python312\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\python312\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tallpra\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\tallpra\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
3.0.2

In [3]:
# Series
# Syntax:
# pd.Series(data, index=index)
# Parameters:
# 1. data: The data to be stored in the Series. It can be a list, dictionary, or NumPy array.
# 2. index: The index to be used for the Series. It can be a list or NumPy array.
#    If not provided, a default integer index will be used.
# Returns:
# A Series object containing the data and index.

In [4]:
population_dict = {
    "California": 39538223,
    "Texas": 29145505,
    "Florida": 21538187,
    "New York": 20201249,
    "Pennsylvania": 13002700,
    "Illinois": 12812508
}
print(population_dict)
print(type(population_dict))

{'California': 39538223, 'Texas': 29145505, 'Florida': 21538187, 'New York': 20201249, 'Pennsylvania': 13002700, 'Illinois': 12812508}
<class 'dict'>

In [5]:
# Create a Series from a Dictionary
print("\nCreate a Series from a Dictionary:")
population_series = pd.Series(population_dict)
print("Series:", population_series)
print("Type:", type(population_series))

Create a Series from a Dictionary:
Series: California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Illinois        12812508
dtype: int64
Type: <class 'pandas.Series'>

In [9]:
# Print the index of the Series
print("\nPrinting the index of the Series:")
print(population_series.index) # index is the Attributes of the Series

Printing the index of the Series:
Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania',
       'Illinois'],
      dtype='str')

In [10]:
# Print the values of the Series
print("Printing the values of the Series:")
print(population_series.values) # values is the Attributes of the Series

Printing the values of the Series:
[39538223 29145505 21538187 20201249 13002700 12812508]

In [11]:
# Create a Series from a List
# Syntax:
# pd.Series(data, index=index)
print("\nCreate a Series from a List:")
s = pd.Series([2, 6, 4, 8, 10])
print("Series:", s)  # Print the Series
print("Type:", type(s))  # Check the type of the Series

Create a Series from a List:
Series: 0     2
1     6
2     4
3     8
4    10
dtype: int64
Type: <class 'pandas.Series'>

In [12]:
# Create a Series from a Tuple
# Syntax:
# pd.Series(data, index=index)
print("\nCreate a Series from a Tuple:")
s = pd.Series((2, 6, 4, 8, 10))
print(s)  # Print the Series
print(type(s))  # Check the type of the Series

Create a Series from a Tuple:
0     2
1     6
2     4
3     8
4    10
dtype: int64
<class 'pandas.Series'>

In [13]:
# We shall be covering the below topic in much more detail later in this notebook
print("First element of the Series:", s[0])  # Access the first element of the Series

First element of the Series: 2

In [15]:
# Create a Series with Custom Index
print("\nCreating a Series with Custom Index:")
s = pd.Series([2, 6, 4, 8, 10], index=["a", "b", "c", "d", "e"])
print(s)  # Print the Series with custom index
print(type(s))  # Check the type of the Series

Creating a Series with Custom Index:
a     2
b     6
c     4
d     8
e    10
dtype: int64
<class 'pandas.Series'>

In [16]:
# We shall be covering the below topic in much more detail later in this notebook
print("First element of the Series with custom index:", s["a"])  # Access the first element of the Series with custom index

First element of the Series with custom index: 2

In [17]:
# Create a Series with a Single Element in a List
s = pd.Series([2])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

0    2
dtype: int64
<class 'pandas.Series'>

In [18]:
# Create a Series with a Single Element
s = pd.Series(2)
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

0    2
dtype: int64
<class 'pandas.Series'>

In [19]:
# Create a Series with a Single Element and Custom Index
s = pd.Series(2, index=["a"])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

a    2
dtype: int64
<class 'pandas.Series'>

In [22]:
# Create a Series with a Single Element and Custom Index - Broadcasted to Multiple Indices
print("\nCreating a Series with a Single Element and Custom Index - Broadcasted to Multiple Indices:")
s = pd.Series(2, index=["a", "b", "c", "d", "e"])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

Creating a Series with a Single Element and Custom Index - Broadcasted to Multiple Indices:
a    2
b    2
c    2
d    2
e    2
dtype: int64
<class 'pandas.Series'>

In [23]:
# Create a Series from a Dictionary with Custom Index
print("\nCreate a Series from a Dictionary with Custom Index:")
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c'
})
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

Create a Series from a Dictionary with Custom Index:
2    a
1    b
3    c
dtype: str
<class 'pandas.Series'>

In [24]:
# Create a Series from a Dictionary of key and value with Custom Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c'
}, index=[1, 2, 3])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

1    b
2    a
3    c
dtype: str
<class 'pandas.Series'>

In [21]:
# Create a Series from a Dictionary with Custom Index and Custom Index - Missing Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c'
}, index=[2, 3])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

2    a
3    c
dtype: object
<class 'pandas.core.series.Series'>

In [25]:
print(population_series)  # Print the Series
print(type(population_series))  # Check the type of the Series
# Print the shape of the Series
print(population_series.shape)  # Print the shape of the Series. the return type is a tuple, which indicates the number of elements in the Series. In this case, it will return (6,), which means there are 6 elements in the Series.

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Illinois        12812508
dtype: int64
<class 'pandas.core.series.Series'>
(6,)

In [27]:
z = population_series.values
print(z)  # Print the values of the Series
print(type(z))  # Check the type of the values of the Series

[39538223 29145505 21538187 20201249 13002700 12812508]
<class 'numpy.ndarray'>

In [28]:
# Shyam

# Create a Series from a Dictionary with Custom Index and Custom Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c',
    "darshan" : 'd'
}, index=["shyam", "darshan", "ingledarshan"])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

shyam           NaN
darshan           d
ingledarshan    NaN
dtype: object
<class 'pandas.core.series.Series'>

In [29]:
# Shyam

# Create a Series from a Dictionary with Custom Index and Custom Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c'
}, index=["shyam", "darshan", "ingledarshan"])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

shyam           NaN
darshan         NaN
ingledarshan    NaN
dtype: object
<class 'pandas.core.series.Series'>

In [30]:
print(population_series)  # Print the Series

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Illinois        12812508
dtype: int64

In [6]:
# Dataframes
# Syntax:
# pd.DataFrame(data, index=index, columns=columns)
# Parameters:
# 1. data: The data to be stored in the DataFrame. It can be a dictionary of Series, a list of dictionaries, or a NumPy array.
# 2. index: The index to be used for the DataFrame. It can be a list or NumPy array.
#    If not provided, a default integer index will be used.
# 3. columns: The columns to be used for the DataFrame. It can be a list or NumPy array.
#    If not provided, the keys of the dictionary will be used as the columns.
# Returns:
# A DataFrame object containing the data, index, and columns.

z = pd.DataFrame(population_series)
z

                     0
California    39538223
Texas         29145505
Florida       21538187
New York      20201249
Pennsylvania  13002700
Illinois      12812508

In [8]:
# Print the shape of the DataFrame
print("\nShape of the DataFrame:")
print(z.shape)  # Print the shape of the DataFrame

Shape of the DataFrame:
(6, 1)

In [11]:
# Syntax:
# pd.DataFrame(data, index=index, columns=columns)

# Let us create a student DataFrame
student_data = {
    "Name": ["John", "Jane", "Jim", "Jack"],
    "Age": [20, 21, 22, 23],
    "Grade": ["A", "B", "C", "D"]
}
student_df = pd.DataFrame(student_data)
student_df

   Name  Age Grade
0  John   20     A
1  Jane   21     B
2   Jim   22     C
3  Jack   23     D

In [12]:
print(student_df)  # Print the DataFrame

   Name  Age Grade
0  John   20     A
1  Jane   21     B
2   Jim   22     C
3  Jack   23     D

In [ ]:
# Lets print the shape of the DataFrame
print(student_df.shape)  # Print the shape of the DataFrame. The return type is a tuple, which indicates the number of rows and columns in the DataFrame. 
# In this case, it will return (4, 3), which means there are 4 rows and 3 columns in the DataFrame.

(4, 3)

In [16]:
print("Printing the DataFrame:")
student_df

Printing the DataFrame:

   Name  Age Grade
0  John   20     A
1  Jane   21     B
2   Jim   22     C
3  Jack   23     D

In [17]:
# Print the index of the DataFrame
print(student_df.index)  # Print the index of the DataFrame. The return type is a RangeIndex object, which indicates the range of the index. In this case, it will return RangeIndex(start=0, stop=4, step=1), which means the index starts at 0, stops at 4, and has a step of 1. This indicates that there are 4 rows in the DataFrame with indices 0, 1, 2, and 3.

RangeIndex(start=0, stop=4, step=1)

In [39]:
# Print the columns of the DataFrame
print(student_df.columns)  # Print the columns of the DataFrame. The return type is an Index object, which indicates the columns of the DataFrame. In this case, it will return Index(['Name', 'Age', 'Grade'], dtype='object'), which means there are 3 columns in the DataFrame with names 'Name', 'Age', and 'Grade'.

Index(['Name', 'Age', 'Grade'], dtype='object')

In [18]:
student_df

   Name  Age Grade
0  John   20     A
1  Jane   21     B
2   Jim   22     C
3  Jack   23     D

In [19]:
# Print the values of the DataFrame
z = student_df.values
print(z)  # Print the values of the DataFrame. The return type is a NumPy array, which contains the values of the DataFrame. In this case, it will return a 2D NumPy array with the values of the DataFrame. Each row of the array corresponds to a row in the DataFrame, and each column of the array corresponds to a column in the DataFrame. The values in the array will be the same as the values in the DataFrame, but they will be stored in a NumPy array format instead of a DataFrame format.
print(type(z))  # Check the type of the values of the DataFrame

[['John' 20 'A']
 ['Jane' 21 'B']
 ['Jim' 22 'C']
 ['Jack' 23 'D']]
<class 'numpy.ndarray'>

In [22]:
import numpy as np
print("\nRandom numbers from a standard normal distribution:")
np.random.randn(5, 3)

Random numbers from a standard normal distribution:

array([[ 0.93785753, -0.02896486,  0.73137957],
       [ 0.09197038,  0.50124016, -1.28584078],
       [-0.59888695,  1.12983986,  0.95445706],
       [-0.26327106, -0.86779815, -1.07129106],
       [ 0.37712543, -0.55060958,  2.40576977]])

In [23]:
# Syntax:
# pd.DataFrame(data, index=index, columns=columns)

import numpy as np
df = pd.DataFrame(data=np.random.randn(5, 3), index=["a", "b", "c", "d", "e"], columns=["A", "B", "C"])
df

          A         B         C
a -0.218813 -0.084951 -1.573845
b  0.788045 -0.357506 -1.895966
c -1.901048 -0.989610  0.264678
d -0.440753 -0.863034 -0.824084
e  0.226036 -1.116106  0.193147

In [77]:
# # https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv

# # Read the CSV file into a DataFrame
# df = pd.read_csv("student_records.csv")
# df

In [24]:
# https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv

# Read the CSV file into a DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv")
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

Below is a **cheat sheet-style reference** of all major file formats supported by **Pandas** for reading data, along with **example syntax** for each.

---

## ✅ 1. CSV (Comma-Separated Values)

```python
import pandas as pd

df = pd.read_csv('data.csv')  # Basic
df = pd.read_csv('data.csv', delimiter=',', encoding='utf-8')  # With options
```

---

## ✅ 2. Excel (`.xls`, `.xlsx`)

```python
df = pd.read_excel('data.xlsx', sheet_name='Sheet1')  # Read specific sheet
```

> Requires: `openpyxl` for `.xlsx`, `xlrd` for `.xls`

---

## ✅ 3. JSON (JavaScript Object Notation)

```python
df = pd.read_json('data.json')  # Assumes records are JSON objects
```

> If using a JSON string or URL:

```python
df = pd.read_json(json_string_or_url, orient='records')
```

---

## ✅ 4. Parquet (Apache columnar format)

```python
df = pd.read_parquet('data.parquet')
```

> Requires: `pyarrow` or `fastparquet`

---

## ✅ 5. SQL (Databases)

```python
import sqlite3

conn = sqlite3.connect('my_database.db')
df = pd.read_sql('SELECT * FROM my_table', conn)
```

> For other DBs like PostgreSQL, use `sqlalchemy` or `psycopg2`.

---

## ✅ 6. HTML (Web Tables)

```python
dfs = pd.read_html('https://example.com/page-with-tables')  # Returns list of DataFrames
```

> Requires: `lxml` or `html5lib`

---

## ✅ 7. Clipboard

```python
df = pd.read_clipboard()  # Paste tabular data copied from Excel or web
```

---

## ✅ 8. ORC (Optimized Row Columnar)

```python
df = pd.read_orc('data.orc')
```

> Requires: `pyarrow`

---

## ✅ 9. Feather

```python
df = pd.read_feather('data.feather')
```

> Fast binary format (good for pipeline stages)

---

## ✅ 10. Pickle (Python serialized object)

```python
df = pd.read_pickle('data.pkl')
```

---

## ✅ 11. XML

```python
df = pd.read_xml('data.xml')
```

> Requires: `lxml`

---

## ✅ 12. Google Sheets (via URL)

```python
sheet_url = 'https://docs.google.com/spreadsheets/d/xyz123/export?format=csv'
df = pd.read_csv(sheet_url)
```

> Ensure the sheet is **shared publicly or accessibly via link**

---

## ✅ 13. Reading from ZIP File (compressed)

```python
df = pd.read_csv('data.zip', compression='zip')
```

> Works similarly for gzip, bz2, xz, etc.

---

## ✅ 14. Reading from S3 / HTTPS / GCS / Azure Blob (Cloud URLs)

```python
df = pd.read_csv('https://bucket.s3.amazonaws.com/data.csv')
df = pd.read_parquet('gs://your-bucket/data.parquet')  # if gcsfs installed
```

> Requires: credentials + cloud FS library (e.g., `s3fs`, `gcsfs`, `adlfs`)

---

In [25]:
# https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv

# Read the CSV file into a DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv")
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [26]:
df.shape

(8, 6)

In [27]:
# https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/Restaurant_Reviews.tsv

restaurant_reviews_df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/Restaurant_Reviews.tsv", sep="\t")
restaurant_reviews_df

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [28]:
restaurant_reviews_df.dtypes # Check the data types of the columns in the DataFrame. The return type is a Series object, which contains the data types of each column in the DataFrame. In this case, it will return a Series with the data types of the 'Review' and 'Liked' columns. The 'Review' column will have a data type of 'object', which indicates that it contains string data, and the 'Liked' column will have a data type of 'int64', which indicates that it contains integer data.

Review      str
Liked     int64
dtype: object

In [29]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [30]:
ss = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/SuperStore.csv")
ss

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,...,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,...,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,...,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,...,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,...,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,...,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Office Supplies,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,...,Binders,0.2,1,4,19.791,19.791,3,0.3750,52.776,52.776
9990,Technology,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,...,Phones,0.0,1,4,2.7279,2.7279,7,0.0300,90.93,90.93
9991,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,...,Binders,0.2,1,4,4.5188,4.5188,2,0.3250,13.904,13.904
9992,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,...,Binders,0.2,1,4,6.475,6.475,2,0.3125,20.72,20.72
9993,Office Supplies,Columbus,United States,CC-12430,Chuck Clark,30/12/17,CA-2017-126221,NaN,Kelly Williams,47201,...,Appliances,0.0,1,6,56.511,56.511,2,0.2700,209.3,209.3

In [31]:
# Set option to display all columns
pd.set_option('display.max_columns', None)
ss

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-ST-10002743,SAFCO Boltless Steel Shelving,2,Central,Central,NaN,741,Home Office,08/01/14,Standard Class,Illinois,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,OFF-AR-10003478,Avery Hi-Liter EverBold Pen Style Fluorescent ...,2,East,East,NaN,1760,Consumer,12/01/14,Standard Class,Pennsylvania,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Office Supplies,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,OFF-BI-10003684,Wilson Jones Legal Size Ring Binders,2,East,East,NaN,909,Consumer,03/01/18,Standard Class,New York,Binders,0.2,1,4,19.791,19.791,3,0.3750,52.776,52.776
9990,Technology,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,TEC-PH-10004774,Gear Head AU3700S Headset,5,East,East,NaN,908,Consumer,03/01/18,Standard Class,New York,Phones,0.0,1,4,2.7279,2.7279,7,0.0300,90.93,90.93
9991,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10002103,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",2,West,West,Yes,1297,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,4.5188,4.5188,2,0.3250,13.904,13.904
9992,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10004632,GBC Binding covers,2,West,West,Yes,1298,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,6.475,6.475,2,0.3125,20.72,20.72
9993,Office Supplies,Columbus,United States,CC-12430,Chuck Clark,30/12/17,CA-2017-126221,NaN,Kelly Williams,47201,OFF-AP-10002457,Eureka The Boss Plus 12-Amp Hard Box Upright V...,2,Central,Central,NaN,646,Home Office,05/01/18,Standard Class,Indiana,Appliances,0.0,1,6,56.511,56.511,2,0.2700,209.3,209.3

In [86]:
# Print the top 5 rows of the DataFrame - head()
ss.head()

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-ST-10002743,SAFCO Boltless Steel Shelving,2,Central,Central,NaN,741,Home Office,08/01/14,Standard Class,Illinois,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,OFF-AR-10003478,Avery Hi-Liter EverBold Pen Style Fluorescent ...,2,East,East,NaN,1760,Consumer,12/01/14,Standard Class,Pennsylvania,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536

In [32]:
# Print the bottom 5 rows of the DataFrame - tail()
ss.tail()

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
9989,Office Supplies,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,OFF-BI-10003684,Wilson Jones Legal Size Ring Binders,2,East,East,NaN,909,Consumer,03/01/18,Standard Class,New York,Binders,0.2,1,4,19.791,19.791,3,0.3750,52.776,52.776
9990,Technology,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,TEC-PH-10004774,Gear Head AU3700S Headset,5,East,East,NaN,908,Consumer,03/01/18,Standard Class,New York,Phones,0.0,1,4,2.7279,2.7279,7,0.0300,90.93,90.93
9991,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10002103,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",2,West,West,Yes,1297,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,4.5188,4.5188,2,0.3250,13.904,13.904
9992,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10004632,GBC Binding covers,2,West,West,Yes,1298,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,6.475,6.475,2,0.3125,20.72,20.72
9993,Office Supplies,Columbus,United States,CC-12430,Chuck Clark,30/12/17,CA-2017-126221,NaN,Kelly Williams,47201,OFF-AP-10002457,Eureka The Boss Plus 12-Amp Hard Box Upright V...,2,Central,Central,NaN,646,Home Office,05/01/18,Standard Class,Indiana,Appliances,0.0,1,6,56.511,56.511,2,0.2700,209.3,209.3

In [33]:
# Print the top 2 rows of the DataFrame - head(2)
ss.head(2)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54

In [34]:
# Print the bottom 7 rows of the DataFrame - tail(7)
ss.tail(7)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
9987,Furniture,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,FUR-BO-10003441,"Bush Westfield Collection Bookcases, Fully Ass...",4,East,East,NaN,907,Consumer,03/01/18,Standard Class,New York,Bookcases,0.2,1,4,12.1176,12.1176,4,0.0375,323.136,323.136
9988,Office Supplies,Loveland,United States,JM-15580,Jill Matthias,30/12/17,CA-2017-156720,NaN,Anna Andreadi,80538,OFF-FA-10003472,Bagged Rubber Bands,2,West,West,NaN,5092,Consumer,03/01/18,Standard Class,Colorado,Fasteners,0.2,1,4,-0.6048,-0.6048,3,-0.2000,3.024,3.024
9989,Office Supplies,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,OFF-BI-10003684,Wilson Jones Legal Size Ring Binders,2,East,East,NaN,909,Consumer,03/01/18,Standard Class,New York,Binders,0.2,1,4,19.791,19.791,3,0.3750,52.776,52.776
9990,Technology,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,TEC-PH-10004774,Gear Head AU3700S Headset,5,East,East,NaN,908,Consumer,03/01/18,Standard Class,New York,Phones,0.0,1,4,2.7279,2.7279,7,0.0300,90.93,90.93
9991,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10002103,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",2,West,West,Yes,1297,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,4.5188,4.5188,2,0.3250,13.904,13.904
9992,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10004632,GBC Binding covers,2,West,West,Yes,1298,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,6.475,6.475,2,0.3125,20.72,20.72
9993,Office Supplies,Columbus,United States,CC-12430,Chuck Clark,30/12/17,CA-2017-126221,NaN,Kelly Williams,47201,OFF-AP-10002457,Eureka The Boss Plus 12-Amp Hard Box Upright V...,2,Central,Central,NaN,646,Home Office,05/01/18,Standard Class,Indiana,Appliances,0.0,1,6,56.511,56.511,2,0.2700,209.3,209.3

In [35]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [36]:
# Select one single column from the DataFrame
# Two ways to select a single column from the DataFrame
# 1. Using the column name as an attribute (not recommended)
# Syntax:
# df.column_name
df.Recommend

0    Yes
1    Yes
2     No
3     No
4     No
5    Yes
6     No
7     No
Name: Recommend, dtype: str

In [37]:
type(df.Recommend)

pandas.Series

In [38]:
# Select one single column from the DataFrame
# Two ways to select a single column from the DataFrame
# 1. Using the column name as an attribute (not recommended)
# Syntax:
# df.column_name
# df.Recommend
# 2. Using the column name as a key (recommended)
# Syntax:
# df["column_name"]
# or
# df['column_name']
df["Recommend"]

0    Yes
1    Yes
2     No
3     No
4     No
5    Yes
6     No
7     No
Name: Recommend, dtype: str

In [39]:
type(df["Recommend"])

pandas.Series

In [95]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [96]:
col_names = df.columns
print(col_names)

Index(['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore',
       'Recommend'],
      dtype='object')

In [42]:
print("Renaming the columns of the DataFrame:")
df.columns = ['Name', 'Overall Grade', 'Obedient', 'Research Score', 'Project Score', 'Recommend']
df

Renaming the columns of the DataFrame:

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [43]:
print("Columns of the DataFrame after renaming:")
df.columns

Columns of the DataFrame after renaming:

Index(['Name', 'Overall Grade', 'Obedient', 'Research Score', 'Project Score',
       'Recommend'],
      dtype='str')

In [44]:
print("Project Score column of the DataFrame:")
print(df["Project Score"])

Project Score column of the DataFrame:
0    85
1    51
2    17
3    71
4    30
5    79
6    59
7    33
Name: Project Score, dtype: int64

In [45]:
print("Project Score column of the DataFrame:")
df['Project Score']

Project Score column of the DataFrame:

0    85
1    51
2    17
3    71
4    30
5    79
6    59
7    33
Name: Project Score, dtype: int64

In [105]:
# df.Project Score # SyntaxError: invalid syntax

In [46]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [47]:
# Select more than one column from the DataFrame - 'Name', 'Overall Grade', 'Recommend'
cols_to_select = ['Name', 'Overall Grade', 'Recommend']
df[cols_to_select]

     Name Overall Grade Recommend
0   Henry             A       Yes
1    John             C       Yes
2   David             F        No
3  Holmes             B        No
4  Marvin             E        No
5   Simon             A       Yes
6  Robert             B        No
7   Trent             C        No

In [48]:
# or
df[['Name', 'Overall Grade', 'Recommend']]

     Name Overall Grade Recommend
0   Henry             A       Yes
1    John             C       Yes
2   David             F        No
3  Holmes             B        No
4  Marvin             E        No
5   Simon             A       Yes
6  Robert             B        No
7   Trent             C        No

In [49]:
df.dtypes

Name                str
Overall Grade       str
Obedient            str
Research Score    int64
Project Score     int64
Recommend           str
dtype: object

In [50]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [51]:
# Print the information about the DataFrame
df.info()  # Print the information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            8 non-null      str
 1   Overall Grade   8 non-null      str
 2   Obedient        8 non-null      str
 3   Research Score  8 non-null      int64
 4   Project Score   8 non-null      int64
 5   Recommend       8 non-null      str
dtypes: int64(2), str(4)
memory usage: 516.0 bytes

In [52]:
# Print the information about the DataFrame
ss.info()  # Print the information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Category            9994 non-null   str
 1   City                9994 non-null   str
 2   Country             9994 non-null   str
 3   Customer ID         9994 non-null   str
 4   Customer Name       9994 non-null   str
 5   Order Date          9994 non-null   str
 6   Order ID            9994 non-null   str
 7   Order ID (Returns)  800 non-null    str
 8   Person              9994 non-null   str
 9   Postal Code         9994 non-null   int64
 10  Product ID          9994 non-null   str
 11  Product Name        9994 non-null   str
 12  Quantity (bin)      9994 non-null   int64
 13  Region              9994 non-null   str
 14  Region (People)     9994 non-null   str
 15  Returned            800 non-null    str
 16  Row ID              9994 non-null   int64
 17  Segment             9994 non-null   str
 18  Ship Date           9994 non-null   str
 19  Ship Mode           9994 non-null   str
 20  State               9994 non-null   str
 21  Sub-Category        9994 non-null   str
 22  Discount            9994 non-null   float64
 23  Number of Records   9994 non-null   int64
 24  OrderUntilShip      9994 non-null   int64
 25  Profit              9994 non-null   str
 26  Profit/1 client     9994 non-null   str
 27  Quantity            9994 non-null   int64
 28  ROS                 9994 non-null   float64
 29  Sales               9994 non-null   str
 30  Sales/1 order       9994 non-null   str
dtypes: float64(2), int64(6), str(23)
memory usage: 2.4 MB

In [53]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [55]:

print("Random sample of 10 values from the Profit column:")
ss.Profit.sample(10)

Random sample of 10 values from the Profit column:

968        9.594
6995      59.998
7775      1.5291
8427    757.4112
2506      8.0712
7615       9.396
7225       4.914
7546    113.9886
3059      8.1168
2175       2.577
Name: Profit, dtype: str

In [56]:
print("DataFrame:")
print(df)

DataFrame:
     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [57]:
# Find all the unique values in the 'Recommend' column - unique()
df['Recommend'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [58]:
type(df['Recommend'].unique())

pandas.arrays.StringArray

In [59]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [61]:
df.Recommend.value_counts() # Count the number of unique values in the 'Recommend' column

# Insight:
# The grant is mostly Not Recommended.
# Very few students have been Recommended for the grant.

Recommend
No     5
Yes    3
Name: count, dtype: int64

In [62]:
ss["Sub-Category"].value_counts() # Count the number of unique values in the 'Sub-Category' column

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [63]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [64]:
df.Recommend.value_counts(normalize=False) # normalize=False is the default value

Recommend
No     5
Yes    3
Name: count, dtype: int64

In [65]:
df.Recommend.value_counts(normalize=True)

Recommend
No     0.625
Yes    0.375
Name: proportion, dtype: float64

In [66]:
print(5/8) # Not Recommended
print(3/8) # Recommended

# Insight:
# 62.5% of the students have been Not Recommended for the grant.
# 37.5% of the students have been Recommended for the grant.
# The grant is mostly Not Recommended, and very few students have been Recommended for the grant.

0.625
0.375

In [67]:
ss["Category"].value_counts(normalize=True)

# Insight:
# more than 80% of business is happening in office and furniture category.

Category
Office Supplies    0.602962
Furniture          0.212227
Technology         0.184811
Name: proportion, dtype: float64

In [68]:
# Find the count of unique values in the 'Recommend' column - nunique()
df.Recommend.nunique()

2

In [69]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [70]:
ss.columns

Index(['Category', 'City', 'Country', 'Customer ID', 'Customer Name',
       'Order Date', 'Order ID', 'Order ID (Returns)', 'Person', 'Postal Code',
       'Product ID', 'Product Name', 'Quantity (bin)', 'Region',
       'Region (People)', 'Returned', 'Row ID', 'Segment', 'Ship Date',
       'Ship Mode', 'State', 'Sub-Category', 'Discount', 'Number of Records',
       'OrderUntilShip', 'Profit', 'Profit/1 client', 'Quantity', 'ROS',
       'Sales', 'Sales/1 order'],
      dtype='str')

In [71]:
# Find the count of unique values in the 'Sub-Category' column - nunique()

ss["Sub-Category"].nunique()
# ss[“Sub-Category”].nunique()

17

In [73]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [74]:
# Find the the number of missing values in each column of the DataFrame - isnull()
ss.isnull().sum()

Category                 0
City                     0
Country                  0
Customer ID              0
Customer Name            0
Order Date               0
Order ID                 0
Order ID (Returns)    9194
Person                   0
Postal Code              0
Product ID               0
Product Name             0
Quantity (bin)           0
Region                   0
Region (People)          0
Returned              9194
Row ID                   0
Segment                  0
Ship Date                0
Ship Mode                0
State                    0
Sub-Category             0
Discount                 0
Number of Records        0
OrderUntilShip           0
Profit                   0
Profit/1 client          0
Quantity                 0
ROS                      0
Sales                    0
Sales/1 order            0
dtype: int64

In [75]:
# Find the the number of missing values in each column of the DataFrame - isnull()
ss.isnull().sum().sort_values(ascending=False)

Order ID (Returns)    9194
Returned              9194
City                     0
Customer ID              0
Customer Name            0
Order Date               0
Category                 0
Order ID                 0
Person                   0
Postal Code              0
Product ID               0
Product Name             0
Quantity (bin)           0
Region                   0
Country                  0
Region (People)          0
Row ID                   0
Segment                  0
Ship Date                0
Ship Mode                0
State                    0
Sub-Category             0
Discount                 0
Number of Records        0
OrderUntilShip           0
Profit                   0
Profit/1 client          0
Quantity                 0
ROS                      0
Sales                    0
Sales/1 order            0
dtype: int64

In [76]:
z = pd.read_csv("student_records.csv")
z

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y           90.0            85       Yes
1    John            C        N           85.0            51       Yes
2   David            F        N           10.0            17        No
3  Holmes            B        Y           75.0            71        No
4  Marvin            E        N            NaN            30        No
5   Simon            A        Y           92.0            79       Yes
6  Robert            B      NaN           60.0            59        No
7   Trent            C        Y           75.0            33        No

In [78]:
print("Number of missing values in each column of the DataFrame:")
z.isnull().sum().sort_values(ascending=False)

Number of missing values in each column of the DataFrame:

ResearchScore    1
Obedient         1
OverallGrade     0
Name             0
ProjectScore     0
Recommend        0
dtype: int64

In [79]:
data = pd.Series([1, 3, 5], index=['a', 'b', 'c'])
data

a    1
b    3
c    5
dtype: int64

In [80]:
data["a"]

np.int64(1)

In [81]:
data["a" : "c"]

a    1
b    3
c    5
dtype: int64

In [82]:
# Indexers in Pandas are used to access and manipulate data in a DataFrame or Series. They allow you to select specific rows and columns based on labels or positions. There are two main types of indexers in Pandas: .loc and .iloc.
# loc is used for label-based indexing, which means you can select rows and columns based on their labels (index names). It allows you to access data using the index labels and column names.
# iloc is used for position-based indexing, which means you can select rows and columns based on their integer positions. It allows you to access data using the integer positions of the rows and columns in the DataFrame or Series.

print(data.loc["a"])
print(data.iloc[0])
print(".."*50)
print(data.loc["b"])
print(data.iloc[1])

print("=="*50)
print(data.iloc[0:2])
print(".."*50)
print(data.loc["a" : "b"]) # SI= "a", EI= "b", both are included in the output

1
1
....................................................................................................
3
3
====================================================================================================
a    1
b    3
dtype: int64
....................................................................................................
a    1
b    3
dtype: int64

In [83]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [84]:
df.index = ["a", "b", "c", "d", "e", "f", "g", "h"]
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
a   Henry             A        Y              90             85       Yes
b    John             C        N              85             51       Yes
c   David             F        N              10             17        No
d  Holmes             B        Y              75             71        No
e  Marvin             E        N              20             30        No
f   Simon             A        Y              92             79       Yes
g  Robert             B        Y              60             59        No
h   Trent             C        Y              75             33        No

In [86]:
print(df.loc["c", "Overall Grade"]) # Syntax: df.loc[row_label, column_label]
print(df.iloc[2, 1]) # Syntax: df.iloc[row_position, column_position]

F
F

In [87]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
a   Henry             A        Y              90             85       Yes
b    John             C        N              85             51       Yes
c   David             F        N              10             17        No
d  Holmes             B        Y              75             71        No
e  Marvin             E        N              20             30        No
f   Simon             A        Y              92             79       Yes
g  Robert             B        Y              60             59        No
h   Trent             C        Y              75             33        No

In [89]:
print("Selecting values by row and column range using .iloc:")
df.iloc[2:6 , 0:4] # SI= 2, EI= 6, SI= 0, EI= 4; SI= 2, EI= 6, SI= 0, EI= 4; both are included in the output

Selecting values by row and column range using .iloc:

     Name Overall Grade Obedient  Research Score
c   David             F        N              10
d  Holmes             B        Y              75
e  Marvin             E        N              20
f   Simon             A        Y              92

In [91]:
print("Selecting values by row and column range using .loc:")
df.loc["c":"f" , "Name":"Research Score"] # SI= "c", EI= "f", both are included in the output; SI= "Name", EI= "Research Score", both are included in the output

Selecting values by row and column range using .loc:

     Name Overall Grade Obedient  Research Score
c   David             F        N              10
d  Holmes             B        Y              75
e  Marvin             E        N              20
f   Simon             A        Y              92

In [92]:
population_series

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Illinois        12812508
dtype: int64

In [93]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
a   Henry             A        Y              90             85       Yes
b    John             C        N              85             51       Yes
c   David             F        N              10             17        No
d  Holmes             B        Y              75             71        No
e  Marvin             E        N              20             30        No
f   Simon             A        Y              92             79       Yes
g  Robert             B        Y              60             59        No
h   Trent             C        Y              75             33        No

In [95]:
print("Adding a new column 'Total Score' to the DataFrame by summing 'Research Score' and 'Project Score':")
df["Total Score"] = df["Research Score"] + df["Project Score"]
df

Adding a new column 'Total Score' to the DataFrame by summing 'Research Score' and 'Project Score':

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [100]:
# Insert 'Total Score' directly before 'Recommend'
print("Inserting a new column 'Total Score TEMP' directly before 'Recommend' by summing 'Research Score' and 'Project Score':")
df.insert(
    loc=5,
    column='Total Score TEMP',
    value=df['Research Score'] + df['Project Score']
)

df

Inserting a new column 'Total Score TEMP' directly before 'Recommend' by summing 'Research Score' and 'Project Score':

ValueError: cannot insert Total Score TEMP, already exists

In [105]:
# Drop the 'Total Score TEMP' column
# drop()
# This drop() can drop a row or a column from the DataFrame. 
# axis=0 is used to drop a row
# axis=1 is used to drop a column

df = df.drop("Total Score TEMP", axis=1)

In [106]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [107]:
# df = df.drop("Total Score TEMP", axis=1)
# or
df.drop("Total Score TEMP", axis=1, inplace=True)
df

KeyError: "['Total Score TEMP'] not found in axis"

In [108]:
df.drop(["Overall Grade", "Research Score", "Total Score"], axis=1)

     Name Obedient  Project Score Recommend
a   Henry        Y             85       Yes
b    John        N             51       Yes
c   David        N             17        No
d  Holmes        Y             71        No
e  Marvin        N             30        No
f   Simon        Y             79       Yes
g  Robert        Y             59        No
h   Trent        Y             33        No

In [109]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [110]:
df.drop(["a"], axis=0) # Drop the row with index 0

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [111]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [112]:
df.drop(["a", "c", "e", "g"], axis=0)

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
b,John,C,N,85,51,Yes,136
d,Holmes,B,Y,75,71,No,146
f,Simon,A,Y,92,79,Yes,171
h,Trent,C,Y,75,33,No,108

# Happy Learning

# Take Home Task

---

# Dataset:

Use this dataset for all tasks:

```python
import pandas as pd

data = {
    "Product": [
        "iPhone 14", "iPhone 14", "iPhone 13", "iPhone 13", "iPhone 12",
        "iPhone 12", "iPhone SE", "iPhone SE", "iPhone 11", "iPhone 11",
        "iPhone XR", "iPhone XR", "iPhone XS", "iPhone XS", "iPhone X",
        "iPhone X", "iPhone 8", "iPhone 8", "iPhone 7", "iPhone 7"
    ],
    "Storage_GB": [
        128, 256, 128, 256, 64,
        128, 64, 128, 64, 128,
        64, 128, 64, 256, 64,
        256, 64, 128, 32, 128
    ],
    "Price_USD": [
        799, 899, 699, 799, 599,
        649, 429, 479, 499, 549,
        399, 449, 999, 1099, 999,
        1099, 449, 499, 349, 399
    ],
    "Color": [
        "Black", "Blue", "Black", "White", "Black",
        "Red", "White", "Black", "Purple", "White",
        "Black", "Blue", "Gold", "Silver", "Black",
        "Silver", "Gold", "Black", "Black", "Gold"
    ],
    "In_Stock": [
        True, True, False, True, True,
        False, True, True, False, True,
        True, False, True, True, False,
        True, True, False, True, True
    ]
}

df = pd.DataFrame(data)
```

---

# 20 Take-Home Tasks

### Section 1: Basic DataFrame Understanding

1. Display the first 5 rows of the dataset.
2. Display the last 3 rows of the dataset.
3. Find the shape of the dataset.
4. List all column names.
5. Display the index of the dataset.

---

### Section 2: Series Extraction

6. Extract the `Price_USD` column as a Series.
7. Extract the `Product` column and display its first 10 values.
8. Create a Series from the `Storage_GB` column and check its type.

---

### Section 3: Selection using loc and iloc

9. Select rows from index 5 to 10 using `iloc`.
10. Select rows where index is 2, 4, and 6 using `loc`.
11. Select only `Product` and `Price_USD` columns using `loc`.
12. Select first 8 rows and first 3 columns using `iloc`.

---

### Section 4: Sorting

13. Sort the dataset based on `Price_USD` in ascending order.
14. Sort the dataset based on `Storage_GB` in descending order.

---

### Section 5: Unique and Value Counts

15. Find all unique values in the `Color` column.
16. Count how many times each product appears using `value_counts()`.

---

### Section 6: Missing Values (Concept Practice)

17. Check if there are any null values in the dataset using `isnull()`.
18. Count total null values column-wise.

---

### Section 7: Drop Operations

19. Drop the `Color` column from the dataset.
20. Drop rows with index 0, 1, and 2.

---

# Important Instruction

“Do not use anything beyond what is taught — no groupby, no apply, no advanced functions.”

---