In [ ]:
# Introduction to Pandas

# Pandas
# Pandas is an important library for data manipulation, wrangling, and analysis.
# What is Data Manipulation?
# Eg: If we had a price column in a dataset, we might want to manipulate the data by converting the prices from one currency to another. This is an example of data manipulation.
# What is Data Wrangling?
# Data wrangling is the process of cleaning and transforming raw data into a format that is suitable for analysis. This can involve tasks such as handling missing values, removing duplicates, and converting data types.
# Eg: If we had a price column in a dataset with values in different formats (e.g., "$10", "10 USD", "10"), we might want to wrangle the data by standardizing the format of the prices. This is an example of data wrangling.
# Eg: If we had a price column in a dataset with some missing values, we might want to wrangle the data by filling in the missing values with the average price. This is another example of data wrangling.
# What is Data Analysis?
# Data analysis is the process of examining, cleaning, transforming, and modeling data to discover useful information, draw conclusions, and support decision-making.
# Eg: If we had a price column in a dataset, we might want to analyze the data by calculating the average price, finding the maximum and minimum prices, and identifying any trends or patterns in the data. This is an example of data analysis.

# Pandas: Pan - Panel Data, das - Data Analysis System
# It is built on top of NumPy and is designed to work seamlessly with it.
# It is also the most widely used library for data analysis in Python.
# It is used in a variety of fields, including finance, economics, statistics, and data science.
# It is also used in machine learning and deep learning.

# Data Structures of Pandas
# Pandas provides two main data structures: Series and DataFrame.
# 1. Series:
#    - A one-dimensional labeled array capable of holding any data type.
#    - It is similar to a list or a dictionary, but it has an index that allows for easy access to the data.
#    - It can be created from a list, dictionary, or NumPy array.
# 2. DataFrame:
#    - A two-dimensional labeled data structure with columns of potentially different types.
#    - It is similar to a spreadsheet or SQL table, or a dictionary of Series objects.
#    - It can be created from a dictionary of Series, a list of dictionaries, or a NumPy array.
#    - It is the most commonly used data structure in Pandas and is used for most data analysis tasks.
#    - It is also the most powerful data structure in Pandas and is used for most data manipulation tasks.
#    - It is used for data wrangling, data cleaning, and data analysis.
#    - It is used for data visualization and data exploration.
#    - It is used for data preprocessing and feature engineering.
#    - It is used for data modeling and machine learning.
#    - It is used for data storage and data retrieval.
#    - It is used for data transformation and data aggregation.
#    - It is used for data merging and data joining.
#    - It is used for data reshaping and data pivoting.
#    - It is used for data filtering and data selection.
#    - It is used for data grouping and data aggregation.
#    - It is used for data sorting and data ordering.
#    - It is used for data indexing and data slicing.
#    - It is used for data concatenation and data appending.
#    - It is used for data splitting and data merging.

In [ ]:
import pandas as pd
print(pd.__version__) # Version of Pandas

# Note:
# Your version of Pandas may be different from the one shown in the output above, as it depends on the version you have installed in your environment.
# However, the concepts and functionalities of Pandas remain consistent across different versions, so you can still follow along with the examples and explanations provided in this introduction to Pandas.
# I can almost guarantee this notebook will work with any version of Pandas.

2.1.4

In [ ]:
# Series
# Syntax:
# pd.Series(data, index=index)
# Parameters:
# 1. data: The data to be stored in the Series. It can be a list, dictionary, or NumPy array.
# 2. index: The index to be used for the Series. It can be a list or NumPy array.
#    If not provided, a default integer index will be used.
# Returns:
# A Series object containing the data and index.

In [ ]:
population_dict = {
    "California": 39538223,
    "Texas": 29145505,
    "Florida": 21538187,
    "New York": 20201249,
    "Pennsylvania": 13002700,
    "Illinois": 12812508
}
print(population_dict)
print(type(population_dict))

{'California': 39538223, 'Texas': 29145505, 'Florida': 21538187, 'New York': 20201249, 'Pennsylvania': 13002700, 'Illinois': 12812508}
<class 'dict'>

In [ ]:
# Create a Series from a Dictionary
population_series = pd.Series(population_dict)
print(population_series)
print(type(population_series))

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Illinois        12812508
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Print the index of the Series
print(population_series.index) # index is the Attributes of the Series

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania',
       'Illinois'],
      dtype='object')

In [ ]:
# Print the values of the Series
print(population_series.values) # values is the Attributes of the Series

[39538223 29145505 21538187 20201249 13002700 12812508]

In [ ]:
# Create a Series from a List
# Syntax:
# pd.Series(data, index=index)
s = pd.Series([2, 6, 4, 8, 10])
print(s)  # Print the Series
print(type(s))  # Check the type of the Series

0     2
1     6
2     4
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series from a Tuple
# Syntax:
# pd.Series(data, index=index)
s = pd.Series((2, 6, 4, 8, 10))
print(s)  # Print the Series
print(type(s))  # Check the type of the Series

0     2
1     6
2     4
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# We shall be covering the below topic in much more detail later in this notebook
print(s[0])  # Access the first element of the Series

2

In [ ]:
# Create a Series with Custom Index
s = pd.Series([2, 6, 4, 8, 10], index=["a", "b", "c", "d", "e"])
print(s)  # Print the Series with custom index
print(type(s))  # Check the type of the Series

a     2
b     6
c     4
d     8
e    10
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# We shall be covering the below topic in much more detail later in this notebook
print(s["a"])  # Access the first element of the Series

2

In [ ]:
# Create a Series with a Single Element in a List
s = pd.Series([2])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

0    2
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series with a Single Element
s = pd.Series(2)
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

0    2
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series with a Single Element and Custom Index
s = pd.Series(2, index=["a"])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

a    2
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series with a Single Element and Custom Index - Broadcasted to Multiple Indices
s = pd.Series(2, index=["a", "b", "c", "d", "e"])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

a    2
b    2
c    2
d    2
e    2
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series from a Dictionary with Custom Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c'
})
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

2    a
1    b
3    c
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series from a Dictionary with Custom Index and Custom Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c'
}, index=[1, 2, 3])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

1    b
2    a
3    c
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series from a Dictionary with Custom Index and Custom Index - Missing Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c'
}, index=[2, 3])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

2    a
3    c
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
print(population_series)  # Print the Series
print(type(population_series))  # Check the type of the Series
# Print the shape of the Series
print(population_series.shape)  # Print the shape of the Series. the return type is a tuple, which indicates the number of elements in the Series. In this case, it will return (6,), which means there are 6 elements in the Series.

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Illinois        12812508
dtype: int64
<class 'pandas.core.series.Series'>
(6,)

In [ ]:
z = population_series.values
print(z)  # Print the values of the Series
print(type(z))  # Check the type of the values of the Series

[39538223 29145505 21538187 20201249 13002700 12812508]
<class 'numpy.ndarray'>

In [ ]:
# Shyam

# Create a Series from a Dictionary with Custom Index and Custom Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c',
    "darshan" : 'd'
}, index=["shyam", "darshan", "ingledarshan"])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

shyam           NaN
darshan           d
ingledarshan    NaN
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
# Shyam

# Create a Series from a Dictionary with Custom Index and Custom Index
s = pd.Series({
    2 : 'a',
    1 : 'b',
    3 : 'c'
}, index=["shyam", "darshan", "ingledarshan"])
print(s)  # Print the Series with a single element
print(type(s))  # Check the type of the Series

shyam           NaN
darshan         NaN
ingledarshan    NaN
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
print(population_series)  # Print the Series

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Illinois        12812508
dtype: int64

In [ ]:
# Dataframes
# Syntax:
# pd.DataFrame(data, index=index, columns=columns)
# Parameters:
# 1. data: The data to be stored in the DataFrame. It can be a dictionary of Series, a list of dictionaries, or a NumPy array.
# 2. index: The index to be used for the DataFrame. It can be a list or NumPy array.
#    If not provided, a default integer index will be used.
# 3. columns: The columns to be used for the DataFrame. It can be a list or NumPy array.
#    If not provided, the keys of the dictionary will be used as the columns.
# Returns:
# A DataFrame object containing the data, index, and columns.

z = pd.DataFrame(population_series)
z

                     0
California    39538223
Texas         29145505
Florida       21538187
New York      20201249
Pennsylvania  13002700
Illinois      12812508

In [ ]:
# Print the shape of the DataFrame
print(z.shape)  # Print the shape of the DataFrame

(6, 1)

In [ ]:
# Syntax:
# pd.DataFrame(data, index=index, columns=columns)

# Let us create a student DataFrame
student_data = {
    "Name": ["John", "Jane", "Jim", "Jack"],
    "Age": [20, 21, 22, 23],
    "Grade": ["A", "B", "C", "D"]
}
student_df = pd.DataFrame(student_data)
student_df

   Name  Age Grade
0  John   20     A
1  Jane   21     B
2   Jim   22     C
3  Jack   23     D

In [ ]:
print(student_df)  # Print the DataFrame

   Name  Age Grade
0  John   20     A
1  Jane   21     B
2   Jim   22     C
3  Jack   23     D

In [ ]:
# Lets print the shape of the DataFrame
print(student_df.shape)  # Print the shape of the DataFrame. The return type is a tuple, which indicates the number of rows and columns in the DataFrame. In this case, it will return (4, 3), which means there are 4 rows and 3 columns in the DataFrame.

(4, 3)

In [ ]:
student_df

   Name  Age Grade
0  John   20     A
1  Jane   21     B
2   Jim   22     C
3  Jack   23     D

In [ ]:
# Print the index of the DataFrame
print(student_df.index)  # Print the index of the DataFrame. The return type is a RangeIndex object, which indicates the range of the index. In this case, it will return RangeIndex(start=0, stop=4, step=1), which means the index starts at 0, stops at 4, and has a step of 1. This indicates that there are 4 rows in the DataFrame with indices 0, 1, 2, and 3.

RangeIndex(start=0, stop=4, step=1)

In [ ]:
# Print the columns of the DataFrame
print(student_df.columns)  # Print the columns of the DataFrame. The return type is an Index object, which indicates the columns of the DataFrame. In this case, it will return Index(['Name', 'Age', 'Grade'], dtype='object'), which means there are 3 columns in the DataFrame with names 'Name', 'Age', and 'Grade'.

Index(['Name', 'Age', 'Grade'], dtype='object')

In [ ]:
student_df

   Name  Age Grade
0  John   20     A
1  Jane   21     B
2   Jim   22     C
3  Jack   23     D

In [ ]:
# Print the values of the DataFrame
z = student_df.values
print(z)  # Print the values of the DataFrame. The return type is a NumPy array, which contains the values of the DataFrame. In this case, it will return a 2D NumPy array with the values of the DataFrame. Each row of the array corresponds to a row in the DataFrame, and each column of the array corresponds to a column in the DataFrame. The values in the array will be the same as the values in the DataFrame, but they will be stored in a NumPy array format instead of a DataFrame format.
print(type(z))  # Check the type of the values of the DataFrame

[['John' 20 'A']
 ['Jane' 21 'B']
 ['Jim' 22 'C']
 ['Jack' 23 'D']]
<class 'numpy.ndarray'>

In [ ]:
import numpy as np
np.random.randn(5, 3)

array([[ 0.58553418,  1.7611658 , -1.10893799],
       [-0.13947874,  0.44914996, -0.06934343],
       [ 0.4541761 , -0.81102945, -0.13507389],
       [ 1.14291335, -0.0725549 , -0.03543241],
       [-0.19097527,  1.22577438, -0.42275655]])

In [ ]:
# Syntax:
# pd.DataFrame(data, index=index, columns=columns)

import numpy as np
df = pd.DataFrame(data=np.random.randn(5, 3), index=["a", "b", "c", "d", "e"], columns=["A", "B", "C"])
df

          A         B         C
a -0.552450  1.113779 -0.063735
b -0.252591 -1.679482  1.528226
c  1.227908  0.680395 -0.610211
d  0.738026  1.713495  0.283419
e -0.471931 -0.335933 -0.561137

In [ ]:
# # https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv

# # Read the CSV file into a DataFrame
# df = pd.read_csv("student_records.csv")
# df

In [ ]:
# https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv

# Read the CSV file into a DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv")
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

Below is a **cheat sheet-style reference** of all major file formats supported by **Pandas** for reading data, along with **example syntax** for each.

---

## ✅ 1. CSV (Comma-Separated Values)

```python
import pandas as pd

df = pd.read_csv('data.csv')  # Basic
df = pd.read_csv('data.csv', delimiter=',', encoding='utf-8')  # With options
```

---

## ✅ 2. Excel (`.xls`, `.xlsx`)

```python
df = pd.read_excel('data.xlsx', sheet_name='Sheet1')  # Read specific sheet
```

> Requires: `openpyxl` for `.xlsx`, `xlrd` for `.xls`

---

## ✅ 3. JSON (JavaScript Object Notation)

```python
df = pd.read_json('data.json')  # Assumes records are JSON objects
```

> If using a JSON string or URL:

```python
df = pd.read_json(json_string_or_url, orient='records')
```

---

## ✅ 4. Parquet (Apache columnar format)

```python
df = pd.read_parquet('data.parquet')
```

> Requires: `pyarrow` or `fastparquet`

---

## ✅ 5. SQL (Databases)

```python
import sqlite3

conn = sqlite3.connect('my_database.db')
df = pd.read_sql('SELECT * FROM my_table', conn)
```

> For other DBs like PostgreSQL, use `sqlalchemy` or `psycopg2`.

---

## ✅ 6. HTML (Web Tables)

```python
dfs = pd.read_html('https://example.com/page-with-tables')  # Returns list of DataFrames
```

> Requires: `lxml` or `html5lib`

---

## ✅ 7. Clipboard

```python
df = pd.read_clipboard()  # Paste tabular data copied from Excel or web
```

---

## ✅ 8. ORC (Optimized Row Columnar)

```python
df = pd.read_orc('data.orc')
```

> Requires: `pyarrow`

---

## ✅ 9. Feather

```python
df = pd.read_feather('data.feather')
```

> Fast binary format (good for pipeline stages)

---

## ✅ 10. Pickle (Python serialized object)

```python
df = pd.read_pickle('data.pkl')
```

---

## ✅ 11. XML

```python
df = pd.read_xml('data.xml')
```

> Requires: `lxml`

---

## ✅ 12. Google Sheets (via URL)

```python
sheet_url = 'https://docs.google.com/spreadsheets/d/xyz123/export?format=csv'
df = pd.read_csv(sheet_url)
```

> Ensure the sheet is **shared publicly or accessibly via link**

---

## ✅ 13. Reading from ZIP File (compressed)

```python
df = pd.read_csv('data.zip', compression='zip')
```

> Works similarly for gzip, bz2, xz, etc.

---

## ✅ 14. Reading from S3 / HTTPS / GCS / Azure Blob (Cloud URLs)

```python
df = pd.read_csv('https://bucket.s3.amazonaws.com/data.csv')
df = pd.read_parquet('gs://your-bucket/data.parquet')  # if gcsfs installed
```

> Requires: credentials + cloud FS library (e.g., `s3fs`, `gcsfs`, `adlfs`)

---

In [ ]:
# https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv

# Read the CSV file into a DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv")
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [ ]:
df.shape

(8, 6)

In [ ]:
# https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/Restaurant_Reviews.tsv

restaurant_reviews_df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/Restaurant_Reviews.tsv", sep="\t")
restaurant_reviews_df

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [ ]:
restaurant_reviews_df.dtypes # Check the data types of the columns in the DataFrame. The return type is a Series object, which contains the data types of each column in the DataFrame. In this case, it will return a Series with the data types of the 'Review' and 'Liked' columns. The 'Review' column will have a data type of 'object', which indicates that it contains string data, and the 'Liked' column will have a data type of 'int64', which indicates that it contains integer data.

Review    object
Liked      int64
dtype: object

In [ ]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [ ]:
ss = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/SuperStore.csv")
ss

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,...,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,...,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,...,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,...,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,...,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,...,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Office Supplies,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,...,Binders,0.2,1,4,19.791,19.791,3,0.3750,52.776,52.776
9990,Technology,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,...,Phones,0.0,1,4,2.7279,2.7279,7,0.0300,90.93,90.93
9991,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,...,Binders,0.2,1,4,4.5188,4.5188,2,0.3250,13.904,13.904
9992,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,...,Binders,0.2,1,4,6.475,6.475,2,0.3125,20.72,20.72
9993,Office Supplies,Columbus,United States,CC-12430,Chuck Clark,30/12/17,CA-2017-126221,NaN,Kelly Williams,47201,...,Appliances,0.0,1,6,56.511,56.511,2,0.2700,209.3,209.3

In [ ]:
# Set option to display all columns
pd.set_option('display.max_columns', None)
ss

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-ST-10002743,SAFCO Boltless Steel Shelving,2,Central,Central,NaN,741,Home Office,08/01/14,Standard Class,Illinois,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,OFF-AR-10003478,Avery Hi-Liter EverBold Pen Style Fluorescent ...,2,East,East,NaN,1760,Consumer,12/01/14,Standard Class,Pennsylvania,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Office Supplies,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,OFF-BI-10003684,Wilson Jones Legal Size Ring Binders,2,East,East,NaN,909,Consumer,03/01/18,Standard Class,New York,Binders,0.2,1,4,19.791,19.791,3,0.3750,52.776,52.776
9990,Technology,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,TEC-PH-10004774,Gear Head AU3700S Headset,5,East,East,NaN,908,Consumer,03/01/18,Standard Class,New York,Phones,0.0,1,4,2.7279,2.7279,7,0.0300,90.93,90.93
9991,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10002103,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",2,West,West,Yes,1297,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,4.5188,4.5188,2,0.3250,13.904,13.904
9992,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10004632,GBC Binding covers,2,West,West,Yes,1298,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,6.475,6.475,2,0.3125,20.72,20.72
9993,Office Supplies,Columbus,United States,CC-12430,Chuck Clark,30/12/17,CA-2017-126221,NaN,Kelly Williams,47201,OFF-AP-10002457,Eureka The Boss Plus 12-Amp Hard Box Upright V...,2,Central,Central,NaN,646,Home Office,05/01/18,Standard Class,Indiana,Appliances,0.0,1,6,56.511,56.511,2,0.2700,209.3,209.3

In [ ]:
# Print the top 5 rows of the DataFrame - head()
ss.head()

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-ST-10002743,SAFCO Boltless Steel Shelving,2,Central,Central,NaN,741,Home Office,08/01/14,Standard Class,Illinois,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,OFF-AR-10003478,Avery Hi-Liter EverBold Pen Style Fluorescent ...,2,East,East,NaN,1760,Consumer,12/01/14,Standard Class,Pennsylvania,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536

In [ ]:
# Print the bottom 5 rows of the DataFrame - tail()
ss.tail()

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
9989,Office Supplies,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,OFF-BI-10003684,Wilson Jones Legal Size Ring Binders,2,East,East,NaN,909,Consumer,03/01/18,Standard Class,New York,Binders,0.2,1,4,19.791,19.791,3,0.3750,52.776,52.776
9990,Technology,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,TEC-PH-10004774,Gear Head AU3700S Headset,5,East,East,NaN,908,Consumer,03/01/18,Standard Class,New York,Phones,0.0,1,4,2.7279,2.7279,7,0.0300,90.93,90.93
9991,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10002103,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",2,West,West,Yes,1297,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,4.5188,4.5188,2,0.3250,13.904,13.904
9992,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10004632,GBC Binding covers,2,West,West,Yes,1298,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,6.475,6.475,2,0.3125,20.72,20.72
9993,Office Supplies,Columbus,United States,CC-12430,Chuck Clark,30/12/17,CA-2017-126221,NaN,Kelly Williams,47201,OFF-AP-10002457,Eureka The Boss Plus 12-Amp Hard Box Upright V...,2,Central,Central,NaN,646,Home Office,05/01/18,Standard Class,Indiana,Appliances,0.0,1,6,56.511,56.511,2,0.2700,209.3,209.3

In [ ]:
# Print the top 2 rows of the DataFrame - head(2)
ss.head(2)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54

In [ ]:
# Print the bottom 7 rows of the DataFrame - tail(7)
ss.tail(7)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
9987,Furniture,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,FUR-BO-10003441,"Bush Westfield Collection Bookcases, Fully Ass...",4,East,East,NaN,907,Consumer,03/01/18,Standard Class,New York,Bookcases,0.2,1,4,12.1176,12.1176,4,0.0375,323.136,323.136
9988,Office Supplies,Loveland,United States,JM-15580,Jill Matthias,30/12/17,CA-2017-156720,NaN,Anna Andreadi,80538,OFF-FA-10003472,Bagged Rubber Bands,2,West,West,NaN,5092,Consumer,03/01/18,Standard Class,Colorado,Fasteners,0.2,1,4,-0.6048,-0.6048,3,-0.2000,3.024,3.024
9989,Office Supplies,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,OFF-BI-10003684,Wilson Jones Legal Size Ring Binders,2,East,East,NaN,909,Consumer,03/01/18,Standard Class,New York,Binders,0.2,1,4,19.791,19.791,3,0.3750,52.776,52.776
9990,Technology,New York City,United States,PO-18865,Patrick O'Donnell,30/12/17,CA-2017-143259,NaN,Chuck Magee,10009,TEC-PH-10004774,Gear Head AU3700S Headset,5,East,East,NaN,908,Consumer,03/01/18,Standard Class,New York,Phones,0.0,1,4,2.7279,2.7279,7,0.0300,90.93,90.93
9991,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10002103,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",2,West,West,Yes,1297,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,4.5188,4.5188,2,0.3250,13.904,13.904
9992,Office Supplies,Fairfield,United States,EB-13975,Erica Bern,30/12/17,CA-2017-115427,CA-2017-115427,Anna Andreadi,94533,OFF-BI-10004632,GBC Binding covers,2,West,West,Yes,1298,Corporate,03/01/18,Standard Class,California,Binders,0.2,1,4,6.475,6.475,2,0.3125,20.72,20.72
9993,Office Supplies,Columbus,United States,CC-12430,Chuck Clark,30/12/17,CA-2017-126221,NaN,Kelly Williams,47201,OFF-AP-10002457,Eureka The Boss Plus 12-Amp Hard Box Upright V...,2,Central,Central,NaN,646,Home Office,05/01/18,Standard Class,Indiana,Appliances,0.0,1,6,56.511,56.511,2,0.2700,209.3,209.3

In [ ]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [ ]:
# Select one single column from the DataFrame
# Two ways to select a single column from the DataFrame
# 1. Using the column name as an attribute (not recommended)
# Syntax:
# df.column_name
df.Recommend

0    Yes
1    Yes
2     No
3     No
4     No
5    Yes
6     No
7     No
Name: Recommend, dtype: object

In [ ]:
type(df.Recommend)

pandas.core.series.Series

In [ ]:
# Select one single column from the DataFrame
# Two ways to select a single column from the DataFrame
# 1. Using the column name as an attribute (not recommended)
# Syntax:
# df.column_name
# df.Recommend
# 2. Using the column name as a key (recommended)
# Syntax:
# df["column_name"]
# or
# df['column_name']
df["Recommend"]

0    Yes
1    Yes
2     No
3     No
4     No
5    Yes
6     No
7     No
Name: Recommend, dtype: object

In [ ]:
type(df["Recommend"])

pandas.core.series.Series

In [ ]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [ ]:
col_names = df.columns
print(col_names)

Index(['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore',
       'Recommend'],
      dtype='object')

In [ ]:
df.columns = ['Name', 'Overall Grade', 'Obedient', 'Research Score', 'Project Score', 'Recommend']
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [ ]:
df.columns

Index(['Name', 'Overall Grade', 'Obedient', 'Research Score', 'Project Score',
       'Recommend'],
      dtype='object')

In [ ]:
df["Project Score"]

0    85
1    51
2    17
3    71
4    30
5    79
6    59
7    33
Name: Project Score, dtype: int64

In [ ]:
df['Project Score']

0    85
1    51
2    17
3    71
4    30
5    79
6    59
7    33
Name: Project Score, dtype: int64

In [ ]:
# df.Project Score # SyntaxError: invalid syntax

In [ ]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [ ]:
# Select more than one column from the DataFrame - 'Name', 'Overall Grade', 'Recommend'
cols_to_select = ['Name', 'Overall Grade', 'Recommend']
df[cols_to_select]

     Name Overall Grade Recommend
0   Henry             A       Yes
1    John             C       Yes
2   David             F        No
3  Holmes             B        No
4  Marvin             E        No
5   Simon             A       Yes
6  Robert             B        No
7   Trent             C        No

In [ ]:
# or
df[['Name', 'Overall Grade', 'Recommend']]

     Name Overall Grade Recommend
0   Henry             A       Yes
1    John             C       Yes
2   David             F        No
3  Holmes             B        No
4  Marvin             E        No
5   Simon             A       Yes
6  Robert             B        No
7   Trent             C        No

In [ ]:
df.dtypes

Name              object
Overall Grade     object
Obedient          object
Research Score     int64
Project Score      int64
Recommend         object
dtype: object

In [ ]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [ ]:
# Print the information about the DataFrame
df.info()  # Print the information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            8 non-null      object
 1   Overall Grade   8 non-null      object
 2   Obedient        8 non-null      object
 3   Research Score  8 non-null      int64
 4   Project Score   8 non-null      int64
 5   Recommend       8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes

In [ ]:
# Print the information about the DataFrame
ss.info()  # Print the information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Category            9994 non-null   object
 1   City                9994 non-null   object
 2   Country             9994 non-null   object
 3   Customer ID         9994 non-null   object
 4   Customer Name       9994 non-null   object
 5   Order Date          9994 non-null   object
 6   Order ID            9994 non-null   object
 7   Order ID (Returns)  800 non-null    object
 8   Person              9994 non-null   object
 9   Postal Code         9994 non-null   int64
 10  Product ID          9994 non-null   object
 11  Product Name        9994 non-null   object
 12  Quantity (bin)      9994 non-null   int64
 13  Region              9994 non-null   object
 14  Region (People)     9994 non-null   object
 15  Returned            800 non-null    object
 16  Row ID              9994 non-null   int64
 17  Segment             9994 non-null   object
 18  Ship Date           9994 non-null   object
 19  Ship Mode           9994 non-null   object
 20  State               9994 non-null   object
 21  Sub-Category        9994 non-null   object
 22  Discount            9994 non-null   float64
 23  Number of Records   9994 non-null   int64
 24  OrderUntilShip      9994 non-null   int64
 25  Profit              9994 non-null   object
 26  Profit/1 client     9994 non-null   object
 27  Quantity            9994 non-null   int64
 28  ROS                 9994 non-null   float64
 29  Sales               9994 non-null   object
 30  Sales/1 order       9994 non-null   object
dtypes: float64(2), int64(6), object(23)
memory usage: 2.4+ MB

In [ ]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [ ]:
ss.Profit.sample(10)

7122      47.0376
2288      12.4416
953        2.5056
2963      18.3908
2998     335.9944
8254       2.6251
1111      -4.1244
2290    -1,181.28
3117      11.4516
4029      21.5824
Name: Profit, dtype: object

In [ ]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [ ]:
# Find all the unique values in the 'Recommend' column - unique()
df['Recommend'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
type(df['Recommend'].unique())

numpy.ndarray

In [ ]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [ ]:
df.Recommend.value_counts() # Count the number of unique values in the 'Recommend' column

# Insight:
# The grant is mostly Not Recommended.
# Very few students have been Recommended for the grant.

Recommend
No     5
Yes    3
Name: count, dtype: int64

In [ ]:
ss["Sub-Category"].value_counts() # Count the number of unique values in the 'Sub-Category' column

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [ ]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [ ]:
df.Recommend.value_counts(normalize=False) # normalize=False is the default value

Recommend
No     5
Yes    3
Name: count, dtype: int64

In [ ]:
df.Recommend.value_counts(normalize=True)

Recommend
No     0.625
Yes    0.375
Name: proportion, dtype: float64

In [ ]:
print(5/8) # Not Recommended
print(3/8) # Recommended

# Insight:
# 62.5% of the students have been Not Recommended for the grant.
# 37.5% of the students have been Recommended for the grant.
# The grant is mostly Not Recommended, and very few students have been Recommended for the grant.

0.625
0.375

In [ ]:
ss["Category"].value_counts(normalize=True)

# Insight:
# more than 80% of business is happening in office and furniture category.

Category
Office Supplies    0.602962
Furniture          0.212227
Technology         0.184811
Name: proportion, dtype: float64

In [ ]:
# Find the count of unique values in the 'Recommend' column - nunique()
df.Recommend.nunique()

2

In [ ]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [ ]:
ss.columns

Index(['Category', 'City', 'Country', 'Customer ID', 'Customer Name',
       'Order Date', 'Order ID', 'Order ID (Returns)', 'Person', 'Postal Code',
       'Product ID', 'Product Name', 'Quantity (bin)', 'Region',
       'Region (People)', 'Returned', 'Row ID', 'Segment', 'Ship Date',
       'Ship Mode', 'State', 'Sub-Category', 'Discount', 'Number of Records',
       'OrderUntilShip', 'Profit', 'Profit/1 client', 'Quantity', 'ROS',
       'Sales', 'Sales/1 order'],
      dtype='object')

In [ ]:
# Find the count of unique values in the 'Sub-Category' column - nunique()

ss["Sub-Category"].nunique()
# ss[“Sub-Category”].nunique()

17

In [ ]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [ ]:
# Find the the number of missing values in each column of the DataFrame - isnull()
ss.isnull().sum()

Category                 0
City                     0
Country                  0
Customer ID              0
Customer Name            0
Order Date               0
Order ID                 0
Order ID (Returns)    9194
Person                   0
Postal Code              0
Product ID               0
Product Name             0
Quantity (bin)           0
Region                   0
Region (People)          0
Returned              9194
Row ID                   0
Segment                  0
Ship Date                0
Ship Mode                0
State                    0
Sub-Category             0
Discount                 0
Number of Records        0
OrderUntilShip           0
Profit                   0
Profit/1 client          0
Quantity                 0
ROS                      0
Sales                    0
Sales/1 order            0
dtype: int64

In [ ]:
# Find the the number of missing values in each column of the DataFrame - isnull()
ss.isnull().sum().sort_values(ascending=False)

Returned              9194
Order ID (Returns)    9194
Row ID                   0
Sales                    0
ROS                      0
Quantity                 0
Profit/1 client          0
Profit                   0
OrderUntilShip           0
Number of Records        0
Discount                 0
Sub-Category             0
State                    0
Ship Mode                0
Ship Date                0
Segment                  0
Category                 0
City                     0
Region (People)          0
Region                   0
Quantity (bin)           0
Product Name             0
Product ID               0
Postal Code              0
Person                   0
Order ID                 0
Order Date               0
Customer Name            0
Customer ID              0
Country                  0
Sales/1 order            0
dtype: int64

In [ ]:
data = pd.Series([1, 3, 5], index=['a', 'b', 'c'])
data

a    1
b    3
c    5
dtype: int64

In [ ]:
data["a"]

1

In [ ]:
data["a" : "c"]

a    1
b    3
c    5
dtype: int64

In [ ]:
# Indexers in Pandas are used to access and manipulate data in a DataFrame or Series. They allow you to select specific rows and columns based on labels or positions. There are two main types of indexers in Pandas: .loc and .iloc.
# loc is used for label-based indexing, which means you can select rows and columns based on their labels (index names). It allows you to access data using the index labels and column names.
# iloc is used for position-based indexing, which means you can select rows and columns based on their integer positions. It allows you to access data using the integer positions of the rows and columns in the DataFrame or Series.

print(data.loc["a"])
print(data.iloc[0])
print(".."*50)
print(data.loc["b"])
print(data.iloc[1])

print("=="*50)
print(data.iloc[0:2])
print(".."*50)
print(data.loc["a" : "b"]) # SI= "a", EI= "b", both are included in the output

1
1
....................................................................................................
3
3
====================================================================================================
a    1
b    3
dtype: int64
....................................................................................................
a    1
b    3
dtype: int64

In [ ]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
0   Henry             A        Y              90             85       Yes
1    John             C        N              85             51       Yes
2   David             F        N              10             17        No
3  Holmes             B        Y              75             71        No
4  Marvin             E        N              20             30        No
5   Simon             A        Y              92             79       Yes
6  Robert             B        Y              60             59        No
7   Trent             C        Y              75             33        No

In [ ]:
df.index = ["a", "b", "c", "d", "e", "f", "g", "h"]
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
a   Henry             A        Y              90             85       Yes
b    John             C        N              85             51       Yes
c   David             F        N              10             17        No
d  Holmes             B        Y              75             71        No
e  Marvin             E        N              20             30        No
f   Simon             A        Y              92             79       Yes
g  Robert             B        Y              60             59        No
h   Trent             C        Y              75             33        No

In [ ]:
print(df.loc["c", "Overall Grade"]) # Syntax: df.loc[row_label, column_label]
print(df.iloc[2, 1]) # Syntax: df.iloc[row_position, column_position]

F
F

In [ ]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
a   Henry             A        Y              90             85       Yes
b    John             C        N              85             51       Yes
c   David             F        N              10             17        No
d  Holmes             B        Y              75             71        No
e  Marvin             E        N              20             30        No
f   Simon             A        Y              92             79       Yes
g  Robert             B        Y              60             59        No
h   Trent             C        Y              75             33        No

In [ ]:
df.iloc[2:6 , 0:4] # SI= 2, EI= 6, SI= 0, EI= 4; SI= 2, EI= 6, SI= 0, EI= 4; both are included in the output

     Name Overall Grade Obedient  Research Score
c   David             F        N              10
d  Holmes             B        Y              75
e  Marvin             E        N              20
f   Simon             A        Y              92

In [ ]:
df.loc["c":"f" , "Name":"Research Score"] # SI= "c", EI= "f", both are included in the output; SI= "Name", EI= "Research Score", both are included in the output

     Name Overall Grade Obedient  Research Score
c   David             F        N              10
d  Holmes             B        Y              75
e  Marvin             E        N              20
f   Simon             A        Y              92

In [ ]:
population_series

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Illinois        12812508
dtype: int64

In [ ]:
df

     Name Overall Grade Obedient  Research Score  Project Score Recommend
a   Henry             A        Y              90             85       Yes
b    John             C        N              85             51       Yes
c   David             F        N              10             17        No
d  Holmes             B        Y              75             71        No
e  Marvin             E        N              20             30        No
f   Simon             A        Y              92             79       Yes
g  Robert             B        Y              60             59        No
h   Trent             C        Y              75             33        No

In [ ]:
df["Total Score"] = df["Research Score"] + df["Project Score"]
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [ ]:
# Insert 'Total Score' directly before 'Recommend'
df.insert(
    loc=5,
    column='Total Score TEMP',
    value=df['Research Score'] + df['Project Score']
)

df

,Name,Overall Grade,Obedient,Research Score,Project Score,Total Score TEMP,Recommend,Total Score
a,Henry,A,Y,90,85,175,Yes,175
b,John,C,N,85,51,136,Yes,136
c,David,F,N,10,17,27,No,27
d,Holmes,B,Y,75,71,146,No,146
e,Marvin,E,N,20,30,50,No,50
f,Simon,A,Y,92,79,171,Yes,171
g,Robert,B,Y,60,59,119,No,119
h,Trent,C,Y,75,33,108,No,108

In [ ]:
# Drop the 'Total Score TEMP' column
# drop()
# This drop() can drop a row or a column from the DataFrame.
# axis=0 is used to drop a row
# axis=1 is used to drop a column

df.drop("Total Score TEMP", axis=1)

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Total Score TEMP,Recommend,Total Score
a,Henry,A,Y,90,85,175,Yes,175
b,John,C,N,85,51,136,Yes,136
c,David,F,N,10,17,27,No,27
d,Holmes,B,Y,75,71,146,No,146
e,Marvin,E,N,20,30,50,No,50
f,Simon,A,Y,92,79,171,Yes,171
g,Robert,B,Y,60,59,119,No,119
h,Trent,C,Y,75,33,108,No,108

In [ ]:
# df = df.drop("Total Score TEMP", axis=1)
# or
df.drop("Total Score TEMP", axis=1, inplace=True)
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [ ]:
df.drop(["Overall Grade", "Research Score", "Total Score"], axis=1)

     Name Obedient  Project Score Recommend
a   Henry        Y             85       Yes
b    John        N             51       Yes
c   David        N             17        No
d  Holmes        Y             71        No
e  Marvin        N             30        No
f   Simon        Y             79       Yes
g  Robert        Y             59        No
h   Trent        Y             33        No

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [ ]:
df.drop(["a"], axis=0) # Drop the row with index 0

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [ ]:
df.drop(["a", "c", "e", "g"], axis=0)

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
b,John,C,N,85,51,Yes,136
d,Holmes,B,Y,75,71,No,146
f,Simon,A,Y,92,79,Yes,171
h,Trent,C,Y,75,33,No,108

# Happy Learning

# Take Home Task

---

# Dataset:

Use this dataset for all tasks:

```python
import pandas as pd

data = {
    "Product": [
        "iPhone 14", "iPhone 14", "iPhone 13", "iPhone 13", "iPhone 12",
        "iPhone 12", "iPhone SE", "iPhone SE", "iPhone 11", "iPhone 11",
        "iPhone XR", "iPhone XR", "iPhone XS", "iPhone XS", "iPhone X",
        "iPhone X", "iPhone 8", "iPhone 8", "iPhone 7", "iPhone 7"
    ],
    "Storage_GB": [
        128, 256, 128, 256, 64,
        128, 64, 128, 64, 128,
        64, 128, 64, 256, 64,
        256, 64, 128, 32, 128
    ],
    "Price_USD": [
        799, 899, 699, 799, 599,
        649, 429, 479, 499, 549,
        399, 449, 999, 1099, 999,
        1099, 449, 499, 349, 399
    ],
    "Color": [
        "Black", "Blue", "Black", "White", "Black",
        "Red", "White", "Black", "Purple", "White",
        "Black", "Blue", "Gold", "Silver", "Black",
        "Silver", "Gold", "Black", "Black", "Gold"
    ],
    "In_Stock": [
        True, True, False, True, True,
        False, True, True, False, True,
        True, False, True, True, False,
        True, True, False, True, True
    ]
}

df = pd.DataFrame(data)
```

---

# 20 Take-Home Tasks

### Section 1: Basic DataFrame Understanding

1. Display the first 5 rows of the dataset.
2. Display the last 3 rows of the dataset.
3. Find the shape of the dataset.
4. List all column names.
5. Display the index of the dataset.

---

### Section 2: Series Extraction

6. Extract the `Price_USD` column as a Series.
7. Extract the `Product` column and display its first 10 values.
8. Create a Series from the `Storage_GB` column and check its type.

---

### Section 3: Selection using loc and iloc

9. Select rows from index 5 to 10 using `iloc`.
10. Select rows where index is 2, 4, and 6 using `loc`.
11. Select only `Product` and `Price_USD` columns using `loc`.
12. Select first 8 rows and first 3 columns using `iloc`.

---

### Section 4: Sorting

13. Sort the dataset based on `Price_USD` in ascending order.
14. Sort the dataset based on `Storage_GB` in descending order.

---

### Section 5: Unique and Value Counts

15. Find all unique values in the `Color` column.
16. Count how many times each product appears using `value_counts()`.

---

### Section 6: Missing Values (Concept Practice)

17. Check if there are any null values in the dataset using `isnull()`.
18. Count total null values column-wise.

---

### Section 7: Drop Operations

19. Drop the `Color` column from the dataset.
20. Drop rows with index 0, 1, and 2.

---

# Important Instruction

“Do not use anything beyond what is taught — no groupby, no apply, no advanced functions.”

---

# Day2 - Pandas

In [ ]:
# Day2 - Pandas

In [ ]:
# Find the the number of missing values in each column of the DataFrame - isnull()
ss.isnull().sum().sort_values(ascending=False)

Returned              9194
Order ID (Returns)    9194
Row ID                   0
Sales                    0
ROS                      0
Quantity                 0
Profit/1 client          0
Profit                   0
OrderUntilShip           0
Number of Records        0
Discount                 0
Sub-Category             0
State                    0
Ship Mode                0
Ship Date                0
Segment                  0
Category                 0
City                     0
Region (People)          0
Region                   0
Quantity (bin)           0
Product Name             0
Product ID               0
Postal Code              0
Person                   0
Order ID                 0
Order Date               0
Customer Name            0
Customer ID              0
Country                  0
Sales/1 order            0
dtype: int64

In [ ]:
ss.shape

(9994, 31)

In [ ]:
per_of_missing_values = 9194/9994
# print(per_of_missing_values)
print(per_of_missing_values*100)
per_of_available_values = 1 - per_of_missing_values
# print(per_of_available_values)
print(per_of_available_values*100)

91.99519711827097
8.004802881729034

In [ ]:
# Find the the percentage of missing values in each column of the DataFrame
# ss.isnull().sum() / ss.shape[0] * 100
import numpy as np
np.round(ss.isnull().sum() / ss.shape[0] * 100, decimals=3).sort_values(ascending=False)

Returned              91.995
Order ID (Returns)    91.995
Row ID                 0.000
Sales                  0.000
ROS                    0.000
Quantity               0.000
Profit/1 client        0.000
Profit                 0.000
OrderUntilShip         0.000
Number of Records      0.000
Discount               0.000
Sub-Category           0.000
State                  0.000
Ship Mode              0.000
Ship Date              0.000
Segment                0.000
Category               0.000
City                   0.000
Region (People)        0.000
Region                 0.000
Quantity (bin)         0.000
Product Name           0.000
Product ID             0.000
Postal Code            0.000
Person                 0.000
Order ID               0.000
Order Date             0.000
Customer Name          0.000
Customer ID            0.000
Country                0.000
Sales/1 order          0.000
dtype: float64

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score
a,Henry,A,Y,90,85,Yes,175
b,John,C,N,85,51,Yes,136
c,David,F,N,10,17,No,27
d,Holmes,B,Y,75,71,No,146
e,Marvin,E,N,20,30,No,50
f,Simon,A,Y,92,79,Yes,171
g,Robert,B,Y,60,59,No,119
h,Trent,C,Y,75,33,No,108

In [ ]:
df["Percentage"] = (df["Total Score"] / 200) * 100
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage
a,Henry,A,Y,90,85,Yes,175,87.5
b,John,C,N,85,51,Yes,136,68.0
c,David,F,N,10,17,No,27,13.5
d,Holmes,B,Y,75,71,No,146,73.0
e,Marvin,E,N,20,30,No,50,25.0
f,Simon,A,Y,92,79,Yes,171,85.5
g,Robert,B,Y,60,59,No,119,59.5
h,Trent,C,Y,75,33,No,108,54.0

In [ ]:
# df = df.sort_values(by="Percentage", ascending=False)
# or
df.sort_values(by="Percentage", ascending=False, inplace=True)
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage
a,Henry,A,Y,90,85,Yes,175,87.5
f,Simon,A,Y,92,79,Yes,171,85.5
d,Holmes,B,Y,75,71,No,146,73.0
b,John,C,N,85,51,Yes,136,68.0
g,Robert,B,Y,60,59,No,119,59.5
h,Trent,C,Y,75,33,No,108,54.0
e,Marvin,E,N,20,30,No,50,25.0
c,David,F,N,10,17,No,27,13.5

In [ ]:
df.reset_index()

,index,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage
0,a,Henry,A,Y,90,85,Yes,175,87.5
1,f,Simon,A,Y,92,79,Yes,171,85.5
2,d,Holmes,B,Y,75,71,No,146,73.0
3,b,John,C,N,85,51,Yes,136,68.0
4,g,Robert,B,Y,60,59,No,119,59.5
5,h,Trent,C,Y,75,33,No,108,54.0
6,e,Marvin,E,N,20,30,No,50,25.0
7,c,David,F,N,10,17,No,27,13.5

In [ ]:
df.reset_index(drop=True, inplace=True)
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage
0,Henry,A,Y,90,85,Yes,175,87.5
1,Simon,A,Y,92,79,Yes,171,85.5
2,Holmes,B,Y,75,71,No,146,73.0
3,John,C,N,85,51,Yes,136,68.0
4,Robert,B,Y,60,59,No,119,59.5
5,Trent,C,Y,75,33,No,108,54.0
6,Marvin,E,N,20,30,No,50,25.0
7,David,F,N,10,17,No,27,13.5

In [ ]:
df["Dummy"] = 100
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Dummy
0,Henry,A,Y,90,85,Yes,175,87.5,100
1,Simon,A,Y,92,79,Yes,171,85.5,100
2,Holmes,B,Y,75,71,No,146,73.0,100
3,John,C,N,85,51,Yes,136,68.0,100
4,Robert,B,Y,60,59,No,119,59.5,100
5,Trent,C,Y,75,33,No,108,54.0,100
6,Marvin,E,N,20,30,No,50,25.0,100
7,David,F,N,10,17,No,27,13.5,100

In [ ]:
# Drop the 'Dummy' column
df.drop("Dummy", axis=1, inplace=True)
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage
0,Henry,A,Y,90,85,Yes,175,87.5
1,Simon,A,Y,92,79,Yes,171,85.5
2,Holmes,B,Y,75,71,No,146,73.0
3,John,C,N,85,51,Yes,136,68.0
4,Robert,B,Y,60,59,No,119,59.5
5,Trent,C,Y,75,33,No,108,54.0
6,Marvin,E,N,20,30,No,50,25.0
7,David,F,N,10,17,No,27,13.5

In [ ]:
# Round the values in the 'Percentage' column
# df["Percentage"] = df["Percentage"].round(2)
# or
df["Percentage"] = np.round(df["Percentage"], decimals=0)
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage
0,Henry,A,Y,90,85,Yes,175,88.0
1,Simon,A,Y,92,79,Yes,171,86.0
2,Holmes,B,Y,75,71,No,146,73.0
3,John,C,N,85,51,Yes,136,68.0
4,Robert,B,Y,60,59,No,119,60.0
5,Trent,C,Y,75,33,No,108,54.0
6,Marvin,E,N,20,30,No,50,25.0
7,David,F,N,10,17,No,27,14.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            8 non-null      object
 1   Overall Grade   8 non-null      object
 2   Obedient        8 non-null      object
 3   Research Score  8 non-null      int64
 4   Project Score   8 non-null      int64
 5   Recommend       8 non-null      object
 6   Total Score     8 non-null      int64
 7   Percentage      8 non-null      float64
dtypes: float64(1), int64(3), object(4)
memory usage: 644.0+ bytes

In [ ]:
df["Percentage"] = df["Percentage"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            8 non-null      object
 1   Overall Grade   8 non-null      object
 2   Obedient        8 non-null      object
 3   Research Score  8 non-null      int64
 4   Project Score   8 non-null      int64
 5   Recommend       8 non-null      object
 6   Total Score     8 non-null      int64
 7   Percentage      8 non-null      int64
dtypes: int64(4), object(4)
memory usage: 644.0+ bytes

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage
0,Henry,A,Y,90,85,Yes,175,88
1,Simon,A,Y,92,79,Yes,171,86
2,Holmes,B,Y,75,71,No,146,73
3,John,C,N,85,51,Yes,136,68
4,Robert,B,Y,60,59,No,119,60
5,Trent,C,Y,75,33,No,108,54
6,Marvin,E,N,20,30,No,50,25
7,David,F,N,10,17,No,27,14

In [ ]:
def cal_pass_fail(per):
    if per >= 40:
        return "Pass"
    else:
        return "Fail"

df["Result"] = df["Percentage"].apply(cal_pass_fail)
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
# Drop the 'Result' column
df.drop(columns=["Result"], inplace=True)
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage
0,Henry,A,Y,90,85,Yes,175,88
1,Simon,A,Y,92,79,Yes,171,86
2,Holmes,B,Y,75,71,No,146,73
3,John,C,N,85,51,Yes,136,68
4,Robert,B,Y,60,59,No,119,60
5,Trent,C,Y,75,33,No,108,54
6,Marvin,E,N,20,30,No,50,25
7,David,F,N,10,17,No,27,14

In [ ]:
# lambda function
# lambda arguments: expression
df["Result"] = df["Percentage"].apply(lambda per: "Pass" if per >= 40 else "Fail")
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

---

### **Pandas Exercises**

---

#### **Section A – Series**

1. Create a Series of 5 smartphone battery capacities using a Python list.
   *Hint: Use `pd.Series([...])`*

2. Create a Series of student names with custom roll numbers as index.
   *Hint: Use `pd.Series([...], index=[...])`*

3. Create a Series from a dictionary where keys are country codes and values are currency names.
   *Hint: Use `pd.Series(dict_data)`*

4. Create a Series using a scalar value 10, repeated for five index values: `"Math", "Science", "English", "History", "PE"`
   *Hint: Use `pd.Series(10, index=[...])`*

5. Create a Series for four department codes and access the 2nd element.
   *Hint: Index using `[1]`*

---

#### **Section B – DataFrame**

**Use the `samsung_tv_data.csv` file for these exercises**

6. Load the Samsung TV dataset using `pd.read_csv()` and display the first 5 rows.
   *Hint: Use `.head()`*

7. Print the column names and shape of the DataFrame.
   *Hint: Use `.columns` and `.shape`*

8. Display the data type of each column.
   *Hint: Use `.dtypes`*

9. Print the data of the last 3 rows using negative indexing.
   *Hint: Use `df[-3:]`*

10. Display all models where the screen size is 55 inches.
    *Hint: Use filtering `df[...]`*

11. Retrieve only the 'Model', 'Type', and 'Price' columns.
    *Hint: Use `df[['Model', 'Type', 'Price']]`*

12. Show all rows where the price is greater than 50000.
    *Hint: Use `df[df['Price'] > 50000]`*

13. Show only rows where the TV has a “5 Star” energy rating.
    *Hint: Filter by string match*

14. Display unique values in the 'Type' column.
    *Hint: Use `.unique()`*

15. Sort the dataset by 'SoldUnits' in descending order.
    *Hint: Use `.sort_values(by='SoldUnits', ascending=False)`*

16. Show TVs with '4K' resolution and screen size ≥ 55 inches.
    *Hint: Use multiple conditions with `&`*

17. Create a new column called `Revenue` as `Price * SoldUnits`.
    *Hint: `df['Revenue'] = df['Price'] * df['SoldUnits']`*

18. Filter TVs that are both of type 'QLED' and have a price above 80000.
    *Hint: Combine two conditions*

19. Count how many models are available for each screen size.
    *Hint: Use `.value_counts()` on `ScreenSize`*

20. Rename the column 'SoldUnits' to 'UnitsSold'.
    *Hint: Use `.rename(columns={...})`*

21. Reset the index after sorting by stock in descending order.
    *Hint: Use `.reset_index(drop=True)`*

22. Filter rows where stock is less than 150 and create a new DataFrame with only these.
    *Hint: Use boolean indexing*

23. Show only the models which have an EnergyRating other than "3 Star".
    *Hint: Use `~` (not operator)*

24. Get the model names of TVs that are both 32-inch and have HD resolution.
    *Hint: Use filtering and select the 'Model' column*

25. Get summary statistics of all numeric columns.
    *Hint: Use `.describe()`*

---

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
# group by
# https://www.w3resource.com/w3r_images/pandas-groupby-split-apply-combine.svg
# Syntax:
# df.groupby(['column1', 'column2']).agg({'column3': 'mean'})

# Find the average marks of student as per "Recommend"
df.groupby("Recommend").agg({"Total Score": "mean"})

           Total Score
Recommend
No           90.000000
Yes         160.666667

In [ ]:
# Find the average marks of student as per "Recommend"
df.groupby("Recommend").agg({"Percentage": "mean"})

           Percentage
Recommend
No          45.200000
Yes         80.666667

In [ ]:
# Find the average marks, sum of marks, count of students as per "Recommend"
df.groupby("Recommend").agg({"Percentage": ["mean", "sum", "count"]})

          Percentage
                mean  sum count
Recommend
No         45.200000  226     5
Yes        80.666667  242     3

In [ ]:
ss.head()

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-ST-10002743,SAFCO Boltless Steel Shelving,2,Central,Central,NaN,741,Home Office,08/01/14,Standard Class,Illinois,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,OFF-AR-10003478,Avery Hi-Liter EverBold Pen Style Fluorescent ...,2,East,East,NaN,1760,Consumer,12/01/14,Standard Class,Pennsylvania,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536

In [ ]:
ss.dtypes

Category               object
City                   object
Country                object
Customer ID            object
Customer Name          object
Order Date             object
Order ID               object
Order ID (Returns)     object
Person                 object
Postal Code             int64
Product ID             object
Product Name           object
Quantity (bin)          int64
Region                 object
Region (People)        object
Returned               object
Row ID                  int64
Segment                object
Ship Date              object
Ship Mode              object
State                  object
Sub-Category           object
Discount              float64
Number of Records       int64
OrderUntilShip          int64
Profit                 object
Profit/1 client        object
Quantity                int64
ROS                   float64
Sales                  object
Sales/1 order          object
dtype: object

In [ ]:
ss.Sales.sample(10)

1885      572.16
6364    2,079.40
5775       34.37
7151     600.558
1001       20.56
7972      872.94
639     1,322.93
187        7.218
8052     138.588
3185        14.6
Name: Sales, dtype: object

In [ ]:
ss["Sales"] = ss["Sales"].str.replace(",", "")
ss.head()

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.54,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-ST-10002743,SAFCO Boltless Steel Shelving,2,Central,Central,NaN,741,Home Office,08/01/14,Standard Class,Illinois,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,OFF-AR-10003478,Avery Hi-Liter EverBold Pen Style Fluorescent ...,2,East,East,NaN,1760,Consumer,12/01/14,Standard Class,Pennsylvania,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536

In [ ]:
ss.Sales.sample(10)

311       22.96
5647      49.53
83       13.272
9244    370.782
9649       38.9
9666      50.04
3559    223.888
1374     257.98
6049    314.088
4609      12.56
Name: Sales, dtype: object

In [ ]:
ss["Sales"] = ss["Sales"].astype(float)
ss.head()

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.540,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-ST-10002743,SAFCO Boltless Steel Shelving,2,Central,Central,NaN,741,Home Office,08/01/14,Standard Class,Illinois,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,05/01/14,CA-2014-141817,NaN,Chuck Magee,19143,OFF-AR-10003478,Avery Hi-Liter EverBold Pen Style Fluorescent ...,2,East,East,NaN,1760,Consumer,12/01/14,Standard Class,Pennsylvania,Art,0.2,1,7,4.884,4.884,3,0.2500,19.536,19.536

In [ ]:
ss.dtypes

Category               object
City                   object
Country                object
Customer ID            object
Customer Name          object
Order Date             object
Order ID               object
Order ID (Returns)     object
Person                 object
Postal Code             int64
Product ID             object
Product Name           object
Quantity (bin)          int64
Region                 object
Region (People)        object
Returned               object
Row ID                  int64
Segment                object
Ship Date              object
Ship Mode              object
State                  object
Sub-Category           object
Discount              float64
Number of Records       int64
OrderUntilShip          int64
Profit                 object
Profit/1 client        object
Quantity                int64
ROS                   float64
Sales                 float64
Sales/1 order          object
dtype: object

In [ ]:
# Find the average Sales as per "Category"
# ss.groupby("Category").agg({"Sales": "mean"})
# or
ss.groupby(["Category"]).agg({"Sales": "mean"})

                      Sales
Category
Furniture        349.834888
Office Supplies  119.324103
Technology       452.709301

In [ ]:
# Find the average Sales as per "Category"
# ss.groupby("Category").agg({"Sales": "mean"})
# or
ss.groupby(["Category"]).agg({"Sales": "mean"}).sort_values(by="Sales", ascending=False)

                      Sales
Category
Technology       452.709301
Furniture        349.834888
Office Supplies  119.324103

In [ ]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.487,-5.487,2,-1.5500,3.540,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [ ]:
ss["Sub-Category"].value_counts()

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [ ]:
# Find the average Sales as per "Category" and "Sub-Category"
ss.groupby(["Category", "Sub-Category"]).agg({"Sales": "mean"})

                                    Sales
Category        Sub-Category
Furniture       Bookcases      503.859696
                Chairs         532.332433
                Furnishings     95.825666
                Tables         648.794712
Office Supplies Appliances     230.755710
                Art             34.068829
                Binders        133.560567
                Envelopes       64.867724
                Fasteners       13.936774
                Labels          34.303055
                Paper           57.284092
                Storage        264.590553
                Supplies       245.650232
Technology      Accessories    215.974606
                Copiers       2198.941912
                Machines      1645.553400
                Phones         371.211550

In [ ]:
ss.dtypes

Category               object
City                   object
Country                object
Customer ID            object
Customer Name          object
Order Date             object
Order ID               object
Order ID (Returns)     object
Person                 object
Postal Code             int64
Product ID             object
Product Name           object
Quantity (bin)          int64
Region                 object
Region (People)        object
Returned               object
Row ID                  int64
Segment                object
Ship Date              object
Ship Mode              object
State                  object
Sub-Category           object
Discount              float64
Number of Records       int64
OrderUntilShip          int64
Profit                 object
Profit/1 client        object
Quantity                int64
ROS                   float64
Sales                 float64
Sales/1 order          object
dtype: object

In [ ]:
ss.Profit.sample(10)

1909      0.2034
7461    -14.8832
6511     23.0864
3182     118.293
8154      59.373
1519      16.704
8990      0.5299
5133      24.857
7176    1,439.98
4288       3.528
Name: Profit, dtype: object

In [ ]:
ss["Profit"] = ss["Profit"].str.replace(",", "").astype(float)
ss.dtypes

Category               object
City                   object
Country                object
Customer ID            object
Customer Name          object
Order Date             object
Order ID               object
Order ID (Returns)     object
Person                 object
Postal Code             int64
Product ID             object
Product Name           object
Quantity (bin)          int64
Region                 object
Region (People)        object
Returned               object
Row ID                  int64
Segment                object
Ship Date              object
Ship Mode              object
State                  object
Sub-Category           object
Discount              float64
Number of Records       int64
OrderUntilShip          int64
Profit                float64
Profit/1 client        object
Quantity                int64
ROS                   float64
Sales                 float64
Sales/1 order          object
dtype: object

In [ ]:
# Find the average Sales as per "Category" and "Sub-Category"
ss.groupby(["Category", "Sub-Category"]).agg({"Sales": "mean" , "Profit": "mean", "Quantity": "mean"})

                                    Sales      Profit  Quantity
Category        Sub-Category
Furniture       Bookcases      503.859696  -15.230486  3.807018
                Chairs         532.332433   43.095894  3.818476
                Furnishings     95.825666   13.645918  3.723093
                Tables         648.794712  -55.565753  3.890282
Office Supplies Appliances     230.755710   38.922764  3.710300
                Art             34.068829    8.200737  3.768844
                Binders        133.560567   19.843590  3.922521
                Envelopes       64.867724   27.418019  3.566929
                Fasteners       13.936774    4.375660  4.211982
                Labels          34.303055   15.236962  3.846154
                Paper           57.284092   24.856620  3.779562
                Storage        264.590553   25.152277  3.732861
                Supplies       245.650232   -6.258415  3.405263
Technology      Accessories    215.974606   54.111788  3.840000
                Copiers       2198.941912  817.909632  3.441176
                Machines      1645.553400   29.432710  3.826087
                Phones         371.211550   50.073939  3.699663

In [ ]:
# Find the average Sales as per "Category" and "Sub-Category"
ss.groupby(["Category", "Sub-Category"]).agg({"Sales": "mean"}).sort_values(by="Sales", ascending=False)

                                    Sales
Category        Sub-Category
Technology      Copiers       2198.941912
                Machines      1645.553400
Furniture       Tables         648.794712
                Chairs         532.332433
                Bookcases      503.859696
Technology      Phones         371.211550
Office Supplies Storage        264.590553
                Supplies       245.650232
                Appliances     230.755710
Technology      Accessories    215.974606
Office Supplies Binders        133.560567
Furniture       Furnishings     95.825666
Office Supplies Envelopes       64.867724
                Paper           57.284092
                Labels          34.303055
                Art             34.068829
                Fasteners       13.936774

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
# Home To office
# Early Morning: 45 min
# Little late: 1:15 hr
# Avg - 1 hr
# STD: +/- 15 min

In [ ]:
# Find the summary statistics of the DataFrame - describe()
df.describe()

       Research Score  Project Score  Total Score  Percentage
count        8.000000       8.000000     8.000000    8.000000
mean        63.375000      53.125000   116.500000   58.500000
std         31.640559      24.752705    53.657645   26.864741
min         10.000000      17.000000    27.000000   14.000000
25%         50.000000      32.250000    93.500000   46.750000
50%         75.000000      55.000000   127.500000   64.000000
75%         86.250000      73.000000   152.250000   76.250000
max         92.000000      85.000000   175.000000   88.000000

In [ ]:
# Find the summary statistics of the DataFrame - describe()
df.describe(include="all")

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
count,8,8,8,8.000000,8.000000,8,8.000000,8.000000,8
unique,8,5,2,NaN,NaN,2,NaN,NaN,2
top,Henry,A,Y,NaN,NaN,No,NaN,NaN,Pass
freq,1,2,5,NaN,NaN,5,NaN,NaN,6
mean,NaN,NaN,NaN,63.375000,53.125000,NaN,116.500000,58.500000,NaN
std,NaN,NaN,NaN,31.640559,24.752705,NaN,53.657645,26.864741,NaN
min,NaN,NaN,NaN,10.000000,17.000000,NaN,27.000000,14.000000,NaN
25%,NaN,NaN,NaN,50.000000,32.250000,NaN,93.500000,46.750000,NaN
50%,NaN,NaN,NaN,75.000000,55.000000,NaN,127.500000,64.000000,NaN
75%,NaN,NaN,NaN,86.250000,73.000000,NaN,152.250000,76.250000,NaN
max,NaN,NaN,NaN,92.000000,85.000000,NaN,175.000000,88.000000,NaN

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
df.groupby(['Recommend'])[['Total Score']].describe()

          Total Score                                                     \
                count        mean        std    min    25%    50%    75%
Recommend
No                5.0   90.000000  49.673937   27.0   50.0  108.0  119.0
Yes               3.0  160.666667  21.455380  136.0  153.5  171.0  173.0


             max
Recommend
No         146.0
Yes        175.0

In [ ]:
df.groupby(['Recommend'])[['Research Score', "Project Score"]].describe()

          Research Score                                                 \
                   count  mean        std   min   25%   50%   75%   max
Recommend
No                   5.0  48.0  30.943497  10.0  20.0  60.0  75.0  75.0
Yes                  3.0  89.0   3.605551  85.0  87.5  90.0  91.0  92.0

          Project Score
                  count       mean        std   min   25%   50%   75%   max
Recommend
No                  5.0  42.000000  22.248595  17.0  30.0  33.0  59.0  71.0
Yes                 3.0  71.666667  18.147543  51.0  65.0  79.0  82.0  85.0

In [ ]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.4870,-5.487,2,-1.5500,3.540,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [ ]:
# Find the average Sales by each "Category, Sub-Category"
ss.groupby(['Category', 'Sub-Category'])[['Sales']].mean()

                                    Sales
Category        Sub-Category
Furniture       Bookcases      503.859696
                Chairs         532.332433
                Furnishings     95.825666
                Tables         648.794712
Office Supplies Appliances     230.755710
                Art             34.068829
                Binders        133.560567
                Envelopes       64.867724
                Fasteners       13.936774
                Labels          34.303055
                Paper           57.284092
                Storage        264.590553
                Supplies       245.650232
Technology      Accessories    215.974606
                Copiers       2198.941912
                Machines      1645.553400
                Phones         371.211550

In [ ]:
# Find the average Sales by each "Category, Sub-Category"
ss.groupby(['Category', 'Sub-Category'])[['Sales']].mean().unstack()

                      Sales                                                \
Sub-Category    Accessories Appliances        Art     Binders   Bookcases
Category
Furniture               NaN        NaN        NaN         NaN  503.859696
Office Supplies         NaN  230.75571  34.068829  133.560567         NaN
Technology       215.974606        NaN        NaN         NaN         NaN

                                                                            \
Sub-Category         Chairs      Copiers  Envelopes  Fasteners Furnishings
Category
Furniture        532.332433          NaN        NaN        NaN   95.825666
Office Supplies         NaN          NaN  64.867724  13.936774         NaN
Technology              NaN  2198.941912        NaN        NaN         NaN

                                                                         \
Sub-Category        Labels   Machines      Paper     Phones     Storage
Category
Furniture              NaN        NaN        NaN        NaN         NaN
Office Supplies  34.303055        NaN  57.284092        NaN  264.590553
Technology             NaN  1645.5534        NaN  371.21155         NaN


Sub-Category       Supplies      Tables
Category
Furniture               NaN  648.794712
Office Supplies  245.650232         NaN
Technology              NaN         NaN

In [ ]:
# Find the average Sales by each "Category, Sub-Category" - pivot_table()
ss.pivot_table(index='Category', columns='Sub-Category', values='Sales', aggfunc='mean')

Sub-Category,Accessories,Appliances,Art,Binders,Bookcases,Chairs,Copiers,Envelopes,Fasteners,Furnishings,Labels,Machines,Paper,Phones,Storage,Supplies,Tables
Category,,,,,,,,,,,,,,,,,
Furniture,NaN,NaN,NaN,NaN,503.859696,532.332433,NaN,NaN,NaN,95.825666,NaN,NaN,NaN,NaN,NaN,NaN,648.794712
Office Supplies,NaN,230.75571,34.068829,133.560567,NaN,NaN,NaN,64.867724,13.936774,NaN,34.303055,NaN,57.284092,NaN,264.590553,245.650232,NaN
Technology,215.974606,NaN,NaN,NaN,NaN,NaN,2198.941912,NaN,NaN,NaN,NaN,1645.5534,NaN,371.21155,NaN,NaN,NaN

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
# Find the names of the students who secured more than 60 marks in the ResearchScore subject
# df["Research Score"] > 60
# df[df["Research Score"] > 60]

# df[df["Research Score"] > 60]["Name"].to_list()
# or
df[df["Research Score"] > 60]["Name"].tolist()

['Henry', 'Simon', 'Holmes', 'John', 'Trent']

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
# Find the names of the students who secured more than 60 marks in the ResearchScore subject and more than 70 marks in the ProjectScore subject
# df["Research Score"] > 60
# df["Project Score"] > 70
df[(df["Research Score"] > 60) & (df["Project Score"] > 70)]["Name"].tolist()

['Henry', 'Simon', 'Holmes']

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
# Find the names of all the students whose name starts with alphabet "H"
# df["Name"].str.startswith("H")
# df[df["Name"].str.startswith("H")]
df[df["Name"].str.startswith("H")]["Name"].tolist()

['Henry', 'Holmes']

In [ ]:
ss.head(3)

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,Product ID,Product Name,Quantity (bin),Region,Region (People),Returned,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,03/01/14,CA-2014-103800,NaN,Kelly Williams,77095,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",2,Central,Central,NaN,7981,Consumer,07/01/14,Standard Class,Texas,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,2,Central,Central,NaN,742,Home Office,08/01/14,Standard Class,Illinois,Binders,0.8,1,4,-5.4870,-5.487,2,-1.5500,3.540,3.54
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,04/01/14,CA-2014-112326,NaN,Kelly Williams,60540,OFF-LA-10003223,Avery 508,2,Central,Central,NaN,740,Home Office,08/01/14,Standard Class,Illinois,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784

In [ ]:
df

,Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
# Rename the 'Name' column to 'First Name'
df.rename(columns={"Name": "First Name"}, inplace=True)
df

,First Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,A,Y,90,85,Yes,175,88,Pass
1,Simon,A,Y,92,79,Yes,171,86,Pass
2,Holmes,B,Y,75,71,No,146,73,Pass
3,John,C,N,85,51,Yes,136,68,Pass
4,Robert,B,Y,60,59,No,119,60,Pass
5,Trent,C,Y,75,33,No,108,54,Pass
6,Marvin,E,N,20,30,No,50,25,Fail
7,David,F,N,10,17,No,27,14,Fail

In [ ]:
# Insert a new column 'Last Name' at index 1 with all different values
df.insert(loc=1, column="Last Name", value=["Smith", "Doe", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller"])
df

,First Name,Last Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry,Smith,A,Y,90,85,Yes,175,88,Pass
1,Simon,Doe,A,Y,92,79,Yes,171,86,Pass
2,Holmes,Johnson,B,Y,75,71,No,146,73,Pass
3,John,Williams,C,N,85,51,Yes,136,68,Pass
4,Robert,Brown,B,Y,60,59,No,119,60,Pass
5,Trent,Jones,C,Y,75,33,No,108,54,Pass
6,Marvin,Garcia,E,N,20,30,No,50,25,Fail
7,David,Miller,F,N,10,17,No,27,14,Fail

In [ ]:
df["Full Name"] = df["First Name"] + " " + df["Last Name"]
df

,First Name,Last Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result,Full Name
0,Henry,Smith,A,Y,90,85,Yes,175,88,Pass,Henry Smith
1,Simon,Doe,A,Y,92,79,Yes,171,86,Pass,Simon Doe
2,Holmes,Johnson,B,Y,75,71,No,146,73,Pass,Holmes Johnson
3,John,Williams,C,N,85,51,Yes,136,68,Pass,John Williams
4,Robert,Brown,B,Y,60,59,No,119,60,Pass,Robert Brown
5,Trent,Jones,C,Y,75,33,No,108,54,Pass,Trent Jones
6,Marvin,Garcia,E,N,20,30,No,50,25,Fail,Marvin Garcia
7,David,Miller,F,N,10,17,No,27,14,Fail,David Miller

In [ ]:
# Drop the 'First Name' and 'Last Name' columns
df.drop(columns=["First Name", "Last Name"], inplace=True)
df

,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result,Full Name
0,A,Y,90,85,Yes,175,88,Pass,Henry Smith
1,A,Y,92,79,Yes,171,86,Pass,Simon Doe
2,B,Y,75,71,No,146,73,Pass,Holmes Johnson
3,C,N,85,51,Yes,136,68,Pass,John Williams
4,B,Y,60,59,No,119,60,Pass,Robert Brown
5,C,Y,75,33,No,108,54,Pass,Trent Jones
6,E,N,20,30,No,50,25,Fail,Marvin Garcia
7,F,N,10,17,No,27,14,Fail,David Miller

In [ ]:
df.columns

Index(['Overall Grade', 'Obedient', 'Research Score', 'Project Score',
       'Recommend', 'Total Score', 'Percentage', 'Result', 'Full Name'],
      dtype='object')

In [ ]:
col_order = ['Full Name', 'Overall Grade', 'Obedient', 'Research Score', 'Project Score', 'Recommend', 'Total Score', 'Percentage', 'Result']
df = df[col_order]
df

,Full Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result
0,Henry Smith,A,Y,90,85,Yes,175,88,Pass
1,Simon Doe,A,Y,92,79,Yes,171,86,Pass
2,Holmes Johnson,B,Y,75,71,No,146,73,Pass
3,John Williams,C,N,85,51,Yes,136,68,Pass
4,Robert Brown,B,Y,60,59,No,119,60,Pass
5,Trent Jones,C,Y,75,33,No,108,54,Pass
6,Marvin Garcia,E,N,20,30,No,50,25,Fail
7,David Miller,F,N,10,17,No,27,14,Fail

In [ ]:
df["Full Name"].str.split(" ")

0       [Henry, Smith]
1         [Simon, Doe]
2    [Holmes, Johnson]
3     [John, Williams]
4      [Robert, Brown]
5       [Trent, Jones]
6     [Marvin, Garcia]
7      [David, Miller]
Name: Full Name, dtype: object

In [ ]:
df["Full Name"].str.split(" ", expand=True)

        0         1
0   Henry     Smith
1   Simon       Doe
2  Holmes   Johnson
3    John  Williams
4  Robert     Brown
5   Trent     Jones
6  Marvin    Garcia
7   David    Miller

In [ ]:
# Split the 'Full Name' column into 'First Name' and 'Last Name' columns
df[["First Name", "Last Name"]] = df["Full Name"].str.split(" ", expand=True)
df

/var/folders/5g/9xpg7d6d4114s98tv10y9rgm0000gn/T/ipykernel_82495/1894132679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["First Name", "Last Name"]] = df["Full Name"].str.split(" ", expand=True)
/var/folders/5g/9xpg7d6d4114s98tv10y9rgm0000gn/T/ipykernel_82495/1894132679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["First Name", "Last Name"]] = df["Full Name"].str.split(" ", expand=True)

,Full Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result,First Name,Last Name
0,Henry Smith,A,Y,90,85,Yes,175,88,Pass,Henry,Smith
1,Simon Doe,A,Y,92,79,Yes,171,86,Pass,Simon,Doe
2,Holmes Johnson,B,Y,75,71,No,146,73,Pass,Holmes,Johnson
3,John Williams,C,N,85,51,Yes,136,68,Pass,John,Williams
4,Robert Brown,B,Y,60,59,No,119,60,Pass,Robert,Brown
5,Trent Jones,C,Y,75,33,No,108,54,Pass,Trent,Jones
6,Marvin Garcia,E,N,20,30,No,50,25,Fail,Marvin,Garcia
7,David Miller,F,N,10,17,No,27,14,Fail,David,Miller

In [ ]:
df.sort_values(by="Last Name", ascending=True)

,Full Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result,First Name,Last Name
4,Robert Brown,B,Y,60,59,No,119,60,Pass,Robert,Brown
1,Simon Doe,A,Y,92,79,Yes,171,86,Pass,Simon,Doe
6,Marvin Garcia,E,N,20,30,No,50,25,Fail,Marvin,Garcia
2,Holmes Johnson,B,Y,75,71,No,146,73,Pass,Holmes,Johnson
5,Trent Jones,C,Y,75,33,No,108,54,Pass,Trent,Jones
7,David Miller,F,N,10,17,No,27,14,Fail,David,Miller
0,Henry Smith,A,Y,90,85,Yes,175,88,Pass,Henry,Smith
3,John Williams,C,N,85,51,Yes,136,68,Pass,John,Williams

In [ ]:
df

,Full Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result,First Name,Last Name
0,Henry Smith,A,Y,90,85,Yes,175,88,Pass,Henry,Smith
1,Simon Doe,A,Y,92,79,Yes,171,86,Pass,Simon,Doe
2,Holmes Johnson,B,Y,75,71,No,146,73,Pass,Holmes,Johnson
3,John Williams,C,N,85,51,Yes,136,68,Pass,John,Williams
4,Robert Brown,B,Y,60,59,No,119,60,Pass,Robert,Brown
5,Trent Jones,C,Y,75,33,No,108,54,Pass,Trent,Jones
6,Marvin Garcia,E,N,20,30,No,50,25,Fail,Marvin,Garcia
7,David Miller,F,N,10,17,No,27,14,Fail,David,Miller

In [ ]:
mean_of_project_score = df["Project Score"].mean()
print(mean_of_project_score)

53.125

In [ ]:
# Filter the students who scored more than the average marks in the Project Score subject
# df["Project Score"] > mean_of_project_score
df_filtered = df[df["Project Score"] > mean_of_project_score]
df_filtered

,Full Name,Overall Grade,Obedient,Research Score,Project Score,Recommend,Total Score,Percentage,Result,First Name,Last Name
0,Henry Smith,A,Y,90,85,Yes,175,88,Pass,Henry,Smith
1,Simon Doe,A,Y,92,79,Yes,171,86,Pass,Simon,Doe
2,Holmes Johnson,B,Y,75,71,No,146,73,Pass,Holmes,Johnson
4,Robert Brown,B,Y,60,59,No,119,60,Pass,Robert,Brown

In [ ]:
df_filtered["Full Name"].tolist()

['Henry Smith', 'Simon Doe', 'Holmes Johnson', 'Robert Brown']

In [ ]:
# Concatenate two DataFrames
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']})
df2 = pd.DataFrame({'C': ['C0', 'C1', 'C2'], 'D': ['D0', 'D1', 'D2']})
print(df1)
print("\n")
print(df2)
pd.concat([df1, df2])
# or
# pd.concat([df1, df2], axis=0)  # Concatenate along rows

# pd.concat([df1, df2], axis=1)  # Concatenate along columns. Default is axis=0

    A   B
0  A0  B0
1  A1  B1
2  A2  B2


    C   D
0  C0  D0
1  C1  D1
2  C2  D2

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2

In [ ]:
# merge()

# The pd.merge() function implements, a number of types of joins:
# a. one to one join
# b. Many to one join
# c. Many to many join

# All three types of joins are assessed via an identical call to the pd.merge() Interface.
# The type of join performed depends on the form of input data.

In [ ]:
# One-to-One Join
# They are similar to column-wise concatenation.

df1 = pd.DataFrame(
    {"employee" : ["Bob", "Jake", "Lisa", "Sue"],
     "group" : ["Accounting", "Engineering", "Engineering", "HR"]}
)

df2 = pd.DataFrame(
    {"employee" : ["Lisa", "Bob", "Jake", "Sue"],
     "hire_date" : [2004, 2008, 2012, 2014]}
)
print(df1)
print("\n")
print(df2)
df3 = pd.merge(df1, df2)
df3

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [ ]:
# Many-to-One Join
# Many-to-One Joins Are the joints in which one of the two key columns contains duplicate entries.

# For the Many-to-One case, the resulting data frame will reserve those duplicate entries as appropriate.

df4 = pd.DataFrame(
    {"group" : ["Accounting", "Engineering", "HR"],
     "supervisor" : ["Carly", "Guido", "Steve"]}
)
print(df3)
print("\n")
print(df4)
pd.merge(df3, df4)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [ ]:
# Many-to-Many Join
# Many-to-Many Joins Are a bit confusing conceptually, but are nevertheless, well defined.
# If the key column in both the left and the right array contains duplicates, then the result is a many to many merge.
df5 = pd.DataFrame(
    {"group" : ["Accounting", "Accounting", "Engineering", "Engineering", "HR", "HR"],
    "skills" : ["math", "spreadsheets", "coding", "linux", "spreadsheets", "organization"]}
)
print(df1)
print("\n")
print(df5)
pd.merge(df3, df5)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

  employee        group  hire_date        skills
0      Bob   Accounting       2008          math
1      Bob   Accounting       2008  spreadsheets
2     Jake  Engineering       2012        coding
3     Jake  Engineering       2012         linux
4     Lisa  Engineering       2004        coding
5     Lisa  Engineering       2004         linux
6      Sue           HR       2014  spreadsheets
7      Sue           HR       2014  organization

In [ ]:
print(df1)
print("\n")
print(df2)
pd.merge(df1, df2, on="employee")
# on - specify the column to join on

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [ ]:
df3 = pd.DataFrame(
    {"name": ["Bob", "Jake", "Lisa", "Sue"],
    "salary": [70000, 80000, 120000, 90000]}
)

print(df1)
print("\n")
print(df3)
# pd.merge(df1, df3, left_on="employee", right_on="name")
pd.merge(df1, df3, left_on="employee", right_on="name").drop("name", axis=1)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [ ]:
df6 = pd.DataFrame(
    {"name": ["Peter", "Paul", "Mary"],
    "food": ["fish", "beans", "bread"]}
)
df7 = pd.DataFrame(
    {"name": ["Mary", "Joseph"],
    "drink": ["wine", "beer"]}
)
print(df6)
print("\n")
print(df7)
pd.merge(df6, df7) # by default, it will perform an inner join

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread


     name drink
0    Mary  wine
1  Joseph  beer

   name   food drink
0  Mary  bread  wine

In [ ]:
pd.merge(df6, df7, how="inner") # inner join

   name   food drink
0  Mary  bread  wine

In [ ]:
# how - specify the type of join
# left - left join
# right - right join
# outer - outer join
# inner - inner join

print(df6)
print("\n")
print(df7)

pd.merge(df6, df7, how="outer") # outer join

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread


     name drink
0    Mary  wine
1  Joseph  beer

     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [ ]:
# Date and TimeDelta in Pandas

In [ ]:
import pandas as pd

# Generate a date range
date_range = pd.date_range(start='2023-01-01', end='2023-01-10', freq='D') # Generate a date range from January 1, 2023 to January 10, 2023 with a frequency of 1 day
# freq - specify the frequency of the date range eg: 'D' for daily, 'W' for weekly, 'M' for monthly, 'Y' for yearly, etc.
print(date_range)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
# Extracting Components from Dates
# Pandas provides the dt accessor to extract various components (Example: day, month, year) from a date column in a DataFrame. This is valuable for time-based analysis when specific date attributes need to be considered.

import pandas as pd

# Assuming 'df' is your DataFrame with a 'Date' column
data = {'Date': ['2023-01-01', '2023-02-15', '2023-03-20']}
df = pd.DataFrame(data)
df

         Date
0  2023-01-01
1  2023-02-15
2  2023-03-20

In [ ]:
df.dtypes

Date    object
dtype: object

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df

        Date
0 2023-01-01
1 2023-02-15
2 2023-03-20

In [ ]:
df.dtypes

Date    datetime64[ns]
dtype: object

In [ ]:
print(df['Date'].dt.day)   # Extract the day component from the 'Date' column
print(df['Date'].dt.month) # Extract the month component from the 'Date' column
print(df['Date'].dt.year)  # Extract the year component from the 'Date' column

0     1
1    15
2    20
Name: Date, dtype: int32
0    1
1    2
2    3
Name: Date, dtype: int32
0    2023
1    2023
2    2023
Name: Date, dtype: int32

In [ ]:
df

        Date
0 2023-01-01
1 2023-02-15
2 2023-03-20

In [ ]:
# Extracting day, month, and year information
df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

df

        Date  Day  Month  Year
0 2023-01-01    1      1  2023
1 2023-02-15   15      2  2023
2 2023-03-20   20      3  2023

In [ ]:
# Extracting weekday and weekend information
df = pd.DataFrame({'Date': pd.date_range(start='2023-01-01', periods=5)}) # Generate a date range starting from January 1, 2023 for 5 periods (5 days)
# periods - specify the number of periods to generate in the date range. eg: periods=5 will generate 5 dates starting from the specified start date.
df

        Date
0 2023-01-01
1 2023-01-02
2 2023-01-03
3 2023-01-04
4 2023-01-05

In [ ]:
print(df['Date'].dt.weekday) # Extract the weekday information from the 'Date' column. The return type is an integer where Monday=0, Tuesday=1, Wednesday=2, Thursday=3, Friday=4, Saturday=5, Sunday=6.

0    6
1    0
2    1
3    2
4    3
Name: Date, dtype: int32

In [ ]:
df['Weekday'] = df['Date'].dt.weekday
df

        Date  Weekday
0 2023-01-01        6
1 2023-01-02        0
2 2023-01-03        1
3 2023-01-04        2
4 2023-01-05        3

In [ ]:
df['IsWeekend'] = df['Date'].dt.weekday // 5 == 1
print(df[['Date', 'Weekday', 'IsWeekend']])

        Date  Weekday  IsWeekend
0 2023-01-01        6       True
1 2023-01-02        0      False
2 2023-01-03        1      False
3 2023-01-04        2      False
4 2023-01-05        3      False

In [ ]:
# Shifting dates forward or backward
df['Date'] = pd.to_datetime(df['Date'])
df

        Date  Weekday  IsWeekend
0 2023-01-01        6       True
1 2023-01-02        0      False
2 2023-01-03        1      False
3 2023-01-04        2      False
4 2023-01-05        3      False

In [ ]:
df['PreviousDate'] = df['Date'] - pd.Timedelta(days=1)
df['NextDate'] = df['Date'] + pd.Timedelta(days=1)
df

        Date  Weekday  IsWeekend PreviousDate   NextDate
0 2023-01-01        6       True   2022-12-31 2023-01-02
1 2023-01-02        0      False   2023-01-01 2023-01-03
2 2023-01-03        1      False   2023-01-02 2023-01-04
3 2023-01-04        2      False   2023-01-03 2023-01-05
4 2023-01-05        3      False   2023-01-04 2023-01-06

In [ ]:
# Timedelta in Pandas:
# Creating a Timedelta
# The Timedelta class in Pandas represents a duration or the difference between two dates or times.
# It can be created by specifying the desired duration, such as days, hours, or minutes.

import pandas as pd

data = {
    'Date': pd.date_range(start='2023-01-01', periods=10, freq='H'),
    'Value1': range(10),
    'Value2': range(10, 20)
}
df = pd.DataFrame(data)
df

                 Date  Value1  Value2
0 2023-01-01 00:00:00       0      10
1 2023-01-01 01:00:00       1      11
2 2023-01-01 02:00:00       2      12
3 2023-01-01 03:00:00       3      13
4 2023-01-01 04:00:00       4      14
5 2023-01-01 05:00:00       5      15
6 2023-01-01 06:00:00       6      16
7 2023-01-01 07:00:00       7      17
8 2023-01-01 08:00:00       8      18
9 2023-01-01 09:00:00       9      19

In [ ]:
# Creating a timedelta of 3 days
delta = pd.Timedelta(days=3) # This creates a timedelta object representing a duration of 3 days.
print(delta)

3 days 00:00:00

In [ ]:
df

                 Date  Value1  Value2
0 2023-01-01 00:00:00       0      10
1 2023-01-01 01:00:00       1      11
2 2023-01-01 02:00:00       2      12
3 2023-01-01 03:00:00       3      13
4 2023-01-01 04:00:00       4      14
5 2023-01-01 05:00:00       5      15
6 2023-01-01 06:00:00       6      16
7 2023-01-01 07:00:00       7      17
8 2023-01-01 08:00:00       8      18
9 2023-01-01 09:00:00       9      19

In [ ]:
# Performing Arithmetic Operations
# Timedelta objects can be used to perform arithmetic operations on dates. For example, adding a timedelta to a date results in a new date. This is useful for calculating future or past dates based on a given time interval.

# Performing arithmetic operations with timedeltas
df['Date'] = pd.to_datetime(df['Date'])
df

                 Date  Value1  Value2
0 2023-01-01 00:00:00       0      10
1 2023-01-01 01:00:00       1      11
2 2023-01-01 02:00:00       2      12
3 2023-01-01 03:00:00       3      13
4 2023-01-01 04:00:00       4      14
5 2023-01-01 05:00:00       5      15
6 2023-01-01 06:00:00       6      16
7 2023-01-01 07:00:00       7      17
8 2023-01-01 08:00:00       8      18
9 2023-01-01 09:00:00       9      19

In [ ]:
df['FutureDate'] = df['Date'] + pd.Timedelta(weeks=2, days=3, hours=12)
df[['Date', 'FutureDate']]

                 Date          FutureDate
0 2023-01-01 00:00:00 2023-01-18 12:00:00
1 2023-01-01 01:00:00 2023-01-18 13:00:00
2 2023-01-01 02:00:00 2023-01-18 14:00:00
3 2023-01-01 03:00:00 2023-01-18 15:00:00
4 2023-01-01 04:00:00 2023-01-18 16:00:00
5 2023-01-01 05:00:00 2023-01-18 17:00:00
6 2023-01-01 06:00:00 2023-01-18 18:00:00
7 2023-01-01 07:00:00 2023-01-18 19:00:00
8 2023-01-01 08:00:00 2023-01-18 20:00:00
9 2023-01-01 09:00:00 2023-01-18 21:00:00

In [ ]:
df

                 Date  Value1  Value2          FutureDate
0 2023-01-01 00:00:00       0      10 2023-01-18 12:00:00
1 2023-01-01 01:00:00       1      11 2023-01-18 13:00:00
2 2023-01-01 02:00:00       2      12 2023-01-18 14:00:00
3 2023-01-01 03:00:00       3      13 2023-01-18 15:00:00
4 2023-01-01 04:00:00       4      14 2023-01-18 16:00:00
5 2023-01-01 05:00:00       5      15 2023-01-18 17:00:00
6 2023-01-01 06:00:00       6      16 2023-01-18 18:00:00
7 2023-01-01 07:00:00       7      17 2023-01-18 19:00:00
8 2023-01-01 08:00:00       8      18 2023-01-18 20:00:00
9 2023-01-01 09:00:00       9      19 2023-01-18 21:00:00

In [ ]:
# Resampling Time Series Data
# Time series data often comes with irregular time intervals. Resampling is the process of changing the frequency of the time series data, either by upsampling (increasing frequency) or downsampling (decreasing frequency).

# Resampling time series data
df.set_index('Date', inplace=True)
df

                     Value1  Value2          FutureDate
Date
2023-01-01 00:00:00       0      10 2023-01-18 12:00:00
2023-01-01 01:00:00       1      11 2023-01-18 13:00:00
2023-01-01 02:00:00       2      12 2023-01-18 14:00:00
2023-01-01 03:00:00       3      13 2023-01-18 15:00:00
2023-01-01 04:00:00       4      14 2023-01-18 16:00:00
2023-01-01 05:00:00       5      15 2023-01-18 17:00:00
2023-01-01 06:00:00       6      16 2023-01-18 18:00:00
2023-01-01 07:00:00       7      17 2023-01-18 19:00:00
2023-01-01 08:00:00       8      18 2023-01-18 20:00:00
2023-01-01 09:00:00       9      19 2023-01-18 21:00:00

In [ ]:
df_resampled = df.select_dtypes(include='number').resample('D').sum()
print(df_resampled)

            Value1  Value2
Date
2023-01-01      45     145

In [ ]:
# Creating a Categorical Variable
# Pandas provides the categorical class to create a categorical variable. Categorical variables are useful when dealing with data that can be divided into distinct, non-numeric categories.

# Creating a categorical variable
categories = ['Low', 'Medium', 'High']
values = ['Low', 'Medium', 'High', 'Low', 'High']

cat_variable = pd.Categorical(values, categories=categories, ordered=True)
print(cat_variable)

['Low', 'Medium', 'High', 'Low', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
# Working with Text Data in Pandas

df = pd.DataFrame({'Column': ['Hello', 'World', 'Python', 'Data Science']})
df

         Column
0         Hello
1         World
2        Python
3  Data Science

In [ ]:
# Calculates the length of each string
df['Length'] = df['Column'].str.len()
df

         Column  Length
0         Hello       5
1         World       5
2        Python       6
3  Data Science      12

In [ ]:
# Assuming 'df' is DataFrame with a 'Column' containing text data
df = pd.DataFrame({'Column': ['Hello', 'World', 'Python', 'Data Science']})
df

         Column
0         Hello
1         World
2        Python
3  Data Science

In [ ]:
# Converts text to lowercase
df['Lowercase'] = df['Column'].str.lower()
df

         Column     Lowercase
0         Hello         hello
1         World         world
2        Python        python
3  Data Science  data science

# Happy Learning

# To do tasks

# CarPrice Dataset Tasks (1–24)

### Basic DataFrame Understanding

1. Load the dataset into a DataFrame and display the first 10 rows.
2. Display the last 5 rows of the dataset.
3. Find the total number of rows and columns.
4. List all column names.

---

### Column Selection (Series + DataFrame)

5. Select the `price` column as a Series.
6. Select `CarName`, `price`, and `horsepower` as a DataFrame.
7. Extract the `fueltype` column and display unique values.

---

### Filtering Rows

8. Filter cars where `price` is greater than 20000.
9. Filter cars where `fueltype` is "gas".
10. Filter cars where `horsepower` is between 100 and 150.
11. Filter cars where `carbody` is "sedan" and `price` > 15000.

---

### Sorting

12. Sort the dataset by `price` in ascending order.
13. Sort the dataset by `price` in descending order.
14. Sort the dataset by `horsepower` and then by `price`.

---

### Basic Aggregations

15. Find the average price of cars.
16. Find the maximum horsepower.
17. Find the minimum engine size.
18. Count the total number of cars with `fueltype` as "diesel".

---

### Value Counts / Frequency

19. Count how many cars belong to each `carbody` type.
20. Count how many cars use each `drivewheel` type.

---

### New Column Creation

21. Create a new column `price_per_hp = price / horsepower`.
22. Create a column `is_expensive` where price > 20000 (True/False).

---

### Column Operations

23. Convert all `CarName` values to lowercase.
24. Replace all occurrences of `"gas"` with `"petrol"` in `fueltype`.

---

# Amazon Dataset Creation

```python
import pandas as pd

data = {
    "product_id": [101, 102, 103, 104, 105],
    "product_name": ["Laptop", "Mobile", "Tablet", "Headphones", "Smartwatch"],
    "price": [80000, 30000, 20000, 5000, 15000],
    "rating": [4.5, 4.2, 4.0, 3.8, 4.3],
    "category": ["Electronics", "Electronics", "Electronics", "Accessories", "Accessories"]
}

df_amazon = pd.DataFrame(data)
```

---

# Amazon Dataset Tasks (25–30)

25. Display all products with price greater than 20000.
26. Select only `product_name` and `price` columns.
27. Find the average rating of all products.
28. Count number of products in each category.
29. Sort products by rating in descending order.
30. Create a new column `discounted_price` assuming 10% discount.

---

# END