In [1]:
# https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv

import pandas as pd
# Read the CSV file into a DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/refs/heads/main/student_records.csv")
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [2]:
df = pd.read_csv("/content/student_records.csv")
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [6]:
dff = pd.read_csv("/content/samsung_tv_data.csv")
dff.head()

      Model  Type  ScreenSize Resolution  Price  SoldUnits  Stock EnergyRating
0      Q60A   LED          43         4K  38999       4500    300       3 Star
1      Q70B  QLED          55         4K  55999       3200    250       4 Star
2    AU7700   LED          43    Full HD  30999       5000    400       3 Star
3      Q95T  QLED          65         4K  89999       2200    100       5 Star
4  TheFrame  QLED          50         4K  73999       2500    120       4 Star

In [7]:
dt = pd.read_csv("samsung_tv_data.csv")
dt.head()

      Model  Type  ScreenSize Resolution  Price  SoldUnits  Stock EnergyRating
0      Q60A   LED          43         4K  38999       4500    300       3 Star
1      Q70B  QLED          55         4K  55999       3200    250       4 Star
2    AU7700   LED          43    Full HD  30999       5000    400       3 Star
3      Q95T  QLED          65         4K  89999       2200    100       5 Star
4  TheFrame  QLED          50         4K  73999       2500    120       4 Star

In [9]:
df_excel = pd.read_excel("/content/SuperStore.xlsx", sheet_name="Sheet1")
df_excel.head()

,Category,City,Country,Customer ID,Customer Name,Order Date,Order ID,Order ID (Returns),Person,Postal Code,...,Sub-Category,Discount,Number of Records,OrderUntilShip,Profit,Profit/1 client,Quantity,ROS,Sales,Sales/1 order
0,Office Supplies,Houston,United States,DP-13000,Darren Powers,2014-01-03,CA-2014-103800,NaN,Kelly Williams,77095,...,Paper,0.2,1,4,5.5512,5.5512,2,0.3375,16.448,16.448
1,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,2014-01-04,CA-2014-112326,NaN,Kelly Williams,60540,...,Binders,0.8,1,4,-5.4870,-5.4870,2,-1.5500,3.540,3.540
2,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,2014-01-04,CA-2014-112326,NaN,Kelly Williams,60540,...,Labels,0.2,1,4,4.2717,4.2717,3,0.3625,11.784,11.784
3,Office Supplies,Naperville,United States,PO-19195,Phillina Ober,2014-01-04,CA-2014-112326,NaN,Kelly Williams,60540,...,Storage,0.2,1,4,-64.7748,-64.7748,3,-0.2375,272.736,272.736
4,Office Supplies,Philadelphia,United States,MB-18085,Mick Brown,2014-01-05,CA-2014-141817,NaN,Chuck Magee,19143,...,Art,0.2,1,7,4.8840,4.8840,3,0.2500,19.536,19.536

In [10]:
# How to read any data from my Google Drive?
# Ans: Mount the drive

In [11]:
df_drive_read = pd.read_csv("/content/drive/MyDrive/Simplilearn/8 IITK AIML Mar 2026 Cohort 46/2 Applied_Data_Science_with_Python (11 classes officially)/Day4 - 26Apr2026/samsung_tv_data.csv")
df_drive_read.head()

      Model  Type  ScreenSize Resolution  Price  SoldUnits  Stock EnergyRating
0      Q60A   LED          43         4K  38999       4500    300       3 Star
1      Q70B  QLED          55         4K  55999       3200    250       4 Star
2    AU7700   LED          43    Full HD  30999       5000    400       3 Star
3      Q95T  QLED          65         4K  89999       2200    100       5 Star
4  TheFrame  QLED          50         4K  73999       2500    120       4 Star

# Happy Learning