In [ ]:
# Parametric vs Non-Parametric Hypothesis Tests

# Suppose you want to test:
# - Is new medicine better?
# - Is new website improving sales?
# - Are two machine outputs different?
# - Did training improve employee performance?

# We use: Hypothesis Testing!

# But now comes a BIG question:
# “What type of test should we use?”

# That depends on:
# Nature of data and assumptions.

# This creates two categories:

| Type                 | Meaning                           |
| -------------------- | --------------------------------- |
| Parametric Tests     | Assume specific data distribution |
| Non-Parametric Tests | Make fewer/no strict assumptions  |

In [2]:
# Parametric Tests
# = “I trust the data follows certain mathematical rules.”

# Non-Parametric Tests
# = “I don’t trust the distribution assumptions.”

In [3]:
# What Are Parametric Tests?

# Parametric tests assume:
# - Data follows normal distribution
# - Mean and standard deviation are meaningful
# - Data is continuous
# - Variance behaves properly

# Parametric tests work well when:
# Data is clean, structured, and approximately normal.

# Real-Life Example — Manufacturing
# Suppose machine bolt lengths are:
#     9.9 mm
#     10.1 mm
#     10.0 mm

# This data is:
# - Continuous
# - Stable
# - Near normal distribution

# Perfect for: Parametric tests

### Common Parametric Tests

| Test                | Purpose                 |
| ------------------- | ----------------------- |
| t-test              | Compare means           |
| ANOVA               | Compare multiple groups |
| Pearson correlation | Relationship analysis   |
| Z-test              | Mean comparison         |

In [4]:
# Example — Employee Training

# Suppose:
# You measure employee productivity before and after training.
# Data looks normally distributed.

# You use:
# Paired t-test (parametric test)

In [6]:
# But There Is a Problem

# Real-world business data is often:
# - Skewed
# - Messy
# - Contains outliers
# - Non-normal

# Then parametric assumptions break.

# Example — Salary Data
# Salaries are highly skewed.

# Few CEOs earn huge amounts.

# Mean gets distorted.

# Normality assumption fails.

# Using parametric tests becomes risky.

# Solution?
# Non-Parametric Tests

In [7]:
# What Are Non-Parametric Tests?

# These tests:
# Do NOT strongly assume normal distribution.
# They are more flexible.

# Non-parametric tests work when:
# - Data is skewed
# - Outliers exist
# - Data is ordinal/categorical
# - Sample size is small
# - Distribution unknown

# Real-Life Example — Customer Ratings
# Ratings:
#     Poor
#     Average
#     Good
#     Excellent

# This is: Ordinal data
# Mean is not very meaningful.
# So we prefer: Non-parametric tests

### Common Non-Parametric Tests

| Test                 | Purpose               |
| -------------------- | --------------------- |
| Mann-Whitney U Test  | Alternative to t-test |
| Wilcoxon Test        | Paired comparison     |
| Kruskal-Wallis Test  | Alternative to ANOVA  |
| Spearman Correlation | Rank relationship     |

In [8]:
# Real-Life Example — Swiggy Ratings
# Suppose customers rate delivery experience: 1–5 stars.

# This data is:
# - Ordinal
# - Skewed
# - Non-normal

# Better suited for: Non-parametric testing

| Parametric                        | Non-Parametric                 |
| --------------------------------- | ------------------------------ |
| Assumes normality                 | No strict normality assumption |
| Uses mean & SD                    | Often uses ranks/medians       |
| More powerful if assumptions true | More robust                    |
| Sensitive to outliers             | Less sensitive                 |

### Use Parametric Tests When:

| Scenario                   | Reason                 |
| -------------------------- | ---------------------- |
| Manufacturing measurements | Normally distributed   |
| Sensor readings            | Continuous stable data |
| Controlled experiments     | Assumptions hold       |

### Use Non-Parametric Tests When:

| Scenario                | Reason                 |
| ----------------------- | ---------------------- |
| Salary analysis         | Skewed                 |
| Customer ratings        | Ordinal                |
| Medical severity scales | Non-normal             |
| Small samples           | Distribution uncertain |

# Non-parametric Statistical hypothesis tests that you need in applied machine learning

## Wilcoxon Sign Test:

It is used to compare the two paired Samples

Paired Samples: Same people, two different situations

H0: There is no significant difference in the calcium level of the patient initial and after 1 weeks.

H1: There is significant difference in the calcium level of the patient initial and after 1 weeks.

If p < 0.05 -> Reject H0

If p >= 0.05 -> Accept H0

In [9]:
import pandas as pd
df = pd.read_excel("Wilcoxon.xlsx", sheet_name=0)

df.head()

,Child,Before_Treatment,After_1_Week_of_Treatment,After_2_Week_of_Treatment
0,1,85,84,104
1,2,70,72,92
2,3,40,41,61
3,4,65,67,87
4,5,80,78,98

In [10]:
from scipy.stats import wilcoxon

stats, p = wilcoxon(df.Before_Treatment, df.After_1_Week_of_Treatment)

print("Stats= ",stats,"\np value= ",p)

Stats=  9.5
p value=  0.578125

Since,  p >= 0.05 -> Accept H0

H0: There is no si
gnificant difference in the calcium level of the patient initial and after 1 weeks.

In [11]:
from scipy.stats import wilcoxon

stats, p = wilcoxon(df.After_1_Week_of_Treatment, df.After_2_Week_of_Treatment)

print("Stats= ",stats,"\np value= ",p)

Stats=  0.0
p value=  0.015625

Since p < 0.05 -> Reject H0

H0: There is no significant difference in the calcium level of the patient after 1 week and after 2 weeks.

## Friedman Test

It is used to compare more than 2 paired samples.

H0: There is no significant difference in the calcium level of the patient initial and after 1 week and also after 2 weeks.

H1: There is significant difference in the calcium level of the patient initial and after 1 week and also after 2 weeks.

If p < 0.05 -> Reject H0

If p >= 0.05 -> Accept H0

In [12]:
from scipy.stats import friedmanchisquare

stats, p = friedmanchisquare(df.Before_Treatment, df.After_1_Week_of_Treatment, df.After_2_Week_of_Treatment)

print("Stats= ", stats, "\np value= ", p)

Stats=  10.57142857142857
p value=  0.005063414171757498

Since p < 0.05 -> Reject H0

H0: There is no significant difference in the calcium level of the patient initial and after 1 week and also after 2 weeks.

## Mann Whitneyu Test

It is used to compare two independent samples.

H0: There is no significant difference in the sales of Design1 and Design2.

H1: There is significant difference in the sales of Design1 and Design2.

If p < 0.05 -> Reject H0

If p >= 0.05 -> Accept H0

In [13]:
import pandas as pd
df = pd.read_excel("Mann_Whitney.xlsx", sheet_name=1)

df.head()

   Design1  Design2
0       11       12
1       17       10
2       16       15
3       14       19
4       15       11

In [14]:
from scipy.stats import mannwhitneyu

stats, p = mannwhitneyu(df.Design1, df.Design2)

print("Stats= ",stats,"\np value= ",p)

Stats=  16.0
p value=  0.5283593272709488

Since, p >= 0.05 -> Accept H0

H0: There is no significant difference in the sales of Design1 and Design2.

## Kruskal Wallis Test:

It is used to compare the two or more independent Samples

H0: There is no significant difference in the sales of Design1, Design2 and Design3.

H1: There is significant difference in the sales of Design1, Design2 and Design3.

If p < 0.05 -> Reject H0

If p >= 0.05 -> Accept H0

In [15]:
import pandas as pd
df = pd.read_excel("Mann_Whitney.xlsx", sheet_name=2)

df.head()

   Design1  Design2  Design3  Showroom
0       11       12       23         1
1       17       10       20         2
2       16       15       18         3
3       14       19       17         4
4       15       11       10         5

In [16]:
from scipy.stats import kruskal

stats, p = kruskal(df.Design1, df.Design2, df.Design3)

print("Stats= ",stats,"\np value= ",p)

Stats=  2.7345323741007226
p value=  0.25480259087913626

Since, p >= 0.05 -> Accept H0

H0: There is no significant difference in the sales of Design1, Design2 and Design3.

## Chi Square Test:

It is used to check the dependency of the variables. Variables should be Categorical.

Variables:

Gender: Male(1) and Female(0)

Smoking: Past Smoker(2), Current Smoker(1) and Non Smoker(0)

H0: There is no dependency between gender and smoking.

H1: There is dependency between gender and smoking.

If p < 0.05 -> Reject H0

If p >= 0.05 -> Accept H0

In [17]:
import pandas as pd
df = pd.read_excel("Chi_Square_Test.xlsx", sheet_name=0)

df.head()

     ids  Gender        Smoking
0  43783  Female      NonSmoker
1  20278  Female      NonSmoker
2  20389  Female      NonSmoker
3  22820    Male            NaN
4  24559    Male  CurrentSmoker

In [18]:
df.isnull().sum()

ids         0
Gender      9
Smoking    24
dtype: int64

In [19]:
df = df.dropna()

df.isnull().sum()

ids        0
Gender     0
Smoking    0
dtype: int64

In [20]:
df.head()

     ids  Gender        Smoking
0  43783  Female      NonSmoker
1  20278  Female      NonSmoker
2  20389  Female      NonSmoker
4  24559    Male  CurrentSmoker
5  28980  Female      NonSmoker

In [21]:
from scipy.stats import chi2_contingency

tab = pd.crosstab(df.Gender, df.Smoking)

tab

Smoking  CurrentSmoker  NonSmoker  PastSmoker
Gender
Female              31        149          13
Male                37        148          24

In [22]:
stats, p, dof, expected = chi2_contingency(tab)

print("Stats= ",stats,"\np value= ",p)

Stats=  3.1712567666931584
p value=  0.20481904779163013

Since, p >= 0.05 -> Accept H0

H0: There is no dependency between gender and smoking.

__ALL THE ABOVE TESTS WERE NON-PARAMETRIC TESTS i.e. ALL THE VARIABLES ARE NOT NORMALLY DISTRIBUTED.__


Lets see the Parametric tests now.

## One Sample T-Test

It is used to compare sample mean with population mean.

Sample Mean ->

Population Mean: Lets assume this as 65

H0: There is no significant difference of mean of students heights against population mean = 65.

H1: There is significant difference of mean of students heights against population mean = 65.

In [23]:
import pandas as pd
df = pd.read_excel("One Sample.xlsx", sheet_name=0)

df.head()

     ids  Height
0  43783   72.35
1  20278   70.66
2  20389   70.68
3  24559   67.43
4  28980   68.45

In [24]:
from scipy.stats import ttest_1samp

stats, p = ttest_1samp(df.Height, 65)

print("Stats= ",stats,"\np value= ",p)

Stats=  11.498800238580099
p value=  1.087893570160242e-26

In [25]:
"{:.35f}".format(float("1.087893570160242e-26"))

'0.00000000000000000000000001087893570'

Since p < 0.05 -> Reject H0

H0: There is no significant difference of mean of students heights against population mean = 65.

## Two Sample T-Test

It is used to compare mean of two paired samples.

H0: There is no significant difference of mean of English and Maths marks.

H1: There is significant difference of mean of English and Maths marks.

In [26]:
import pandas as pd
df = pd.read_excel("Two Paired Sample.xlsx", sheet_name=0)

df.head()

     ids  English   Math
0  43783    88.24  60.02
1  20278    89.45  70.19
2  20389    96.73  71.20
3  22820    74.06  55.89
4  24559    82.61  65.52

In [27]:
from scipy.stats import ttest_rel

stats, p = ttest_rel(df.English, df.Math)

print("Stats= ",stats,"\np value= ",p)

Stats=  36.312568981719856
p value=  3.0710987192210606e-128

Since p < 0.05 -> Reject H0

H0: There is no significant difference of mean of English and Maths marks.

## Two Sample Independent T-Test

It is used to compare mean of two independent samples.

H0: There is no significant difference in the mean of duration between Athlete and Non-Athlete.

H1: There is significant difference in the mean of duration between Athlete and Non-Athlete.

In [29]:
import pandas as pd
df = pd.read_excel("Independent Sample.xlsx", sheet_name=3)

df.head()

   Nonathelete  Athelete
0     0.004413  0.004462
1     0.004872  0.005146
2     0.008851  0.004023
3     0.006508  0.003941
4     0.006314  0.004764

In [30]:
df.shape

(166, 2)

In [31]:
from scipy.stats import ttest_ind

stats, p = ttest_ind(df.Nonathelete, df.Athelete)

print("Stats= ",stats,"\np value= ",p)

Stats=  13.368790432137319
p value=  7.116633157230895e-33

Since p < 0.05 -> Reject H0

H0: There is no significant difference in the mean of duration between Athlete and Non-Athlete.

## One way Anova Test

H0:  because of Promotion, there is a no significant impact on the Sales.

H1:  because of Promotion, there is a significant impact on the Sales

In [32]:
import pandas as pd
df = pd.read_excel("ANCOVA1.xlsx", sheet_name=0)

df.head()

   Store Number  Sales  Promotion  Coupon  ClietelRatings
0             1     10          1       1               9
1             2      9          1       1              10
2             3     10          1       1               8
3             4      8          1       1               4
4             5      9          1       1               6

In [34]:
df.columns

# Index(['Store Number', 'Sales', 'Promotion', 'Coupon', 'ClietelRatings'], dtype='object')
# Store Number: Unique identifier for each store.
# Sales: Total sales amount for each store.
# Promotion: Binary variable indicating if the store had a promotion (1) or not (0).
# Coupon: Binary variable indicating if the store offered coupons (1) or not (0).
# ClietelRatings: Customer ratings for the store (1 to 10 scale).

Index(['Store Number', 'Sales', 'Promotion', 'Coupon', 'ClietelRatings'], dtype='object')

Sales -> Dependent Variable

Promotion -> Independent Variable

In [35]:
df.Promotion.value_counts()

Promotion
1    10
2    10
3    10
Name: count, dtype: int64

In [36]:
import statsmodels.api as sm
from statsmodels.formula.api import ols # OLS is Ordinary Least Square
model = ols('Sales~C(Promotion)',df).fit() # C means Promotion is Categorical variable

In [37]:
oneway = sm.stats.anova_lm(model, type=2)
# type=1 is Regression
# type=2 is for ANOVA and ANCOVA
# type=3 is for Discriminant Analysis

print(oneway)

                df      sum_sq    mean_sq          F    PR(>F)
C(Promotion)   2.0  106.066667  53.033333  17.943609  0.000011
Residual      27.0   79.800000   2.955556        NaN       NaN

Between Variation is 106.066667 and within variation is 79.800000  

p-value is 0.000011 which is <0.05

Therefore we can say because of Promotion, there is a significant impact on the Sales.

## Two way Anova Test

In [38]:
model = ols('Sales~C(Promotion)+C(Coupon)',df).fit()

In [39]:
twoway = sm.stats.anova_lm(model, type=2)

print(twoway)

                df      sum_sq    mean_sq          F        PR(>F)
C(Promotion)   2.0  106.066667  53.033333  52.098237  8.032739e-10
C(Coupon)      1.0   53.333333  53.333333  52.392947  1.095036e-07
Residual      26.0   26.466667   1.017949        NaN           NaN

p value of Promotion is 8.032739e-10 and Coupon is 1.095036e-07 i.e. both of these are less than 0.05

Therefore we can say that both the variables are significantly affecting the Sales.

## Ancova

Dependent Variable -> Sales

Independent Variable -> Promotion, Coupon, Client Rating

In [40]:
model = ols('Sales~C(Promotion)+C(Coupon)+ClietelRatings',df).fit()

In [41]:
ancova = sm.stats.anova_lm(model, type=2)

print(ancova)

                  df      sum_sq    mean_sq          F        PR(>F)
C(Promotion)     2.0  106.066667  53.033333  51.732296  1.301539e-09
C(Coupon)        1.0   53.333333  53.333333  52.024936  1.471502e-07
ClietelRatings   1.0    0.837931   0.837931   0.817375  3.745789e-01
Residual        25.0   25.628736   1.025149        NaN           NaN

p value of Promotion is 1.301539e-09 and Coupon is 1.471502e-07 i.e. both of these are less than 0.05

whereas p value of ClietelRatings is 3.745789e-01 which is >0.05

Therefore we can say that both Promotion and Coupon variables are significantly affecting the Sales whereas ClietelRatings have no significant impact on the Sales.

### Happy Learning!!!

# Day11 - 23rd May continued

In [1]:
# Read the CSV and Display the Data
import pandas as pd

# Load dataset
df = pd.read_csv("b2b_model_test_data.csv")

df.shape  # Check the shape of the DataFrame

(15, 5)

In [3]:
df
#  B2B scenario
# -Two ML models (A & B) predict lead conversion.
# -Each client has a Region and an actual conversion status (Lead_Converted).

             Client  Model_A_Accuracy  Model_B_Accuracy  Lead_Converted Region
0         AlphaTech              0.83              0.80               1  North
1          BetaCorp              0.78              0.75               1  South
2    GammaSolutions              0.81              0.79               0   East
3          DeltaInc              0.76              0.74               0   West
4        EpsilonLLC              0.85              0.83               1  North
5         ZetaWorks              0.79              0.76               1  South
6         EtaGlobal              0.77              0.75               0   East
7         ThetaTech              0.82              0.80               1   West
8   IotaEnterprises              0.84              0.82               1  North
9         KappaSoft              0.80              0.77               0  South
10   LambdaNetworks              0.79              0.76               0   East
11        MuSystems              0.83              0.81               1   West
12         NuLogics              0.81              0.78               1  North
13       XiServices              0.76              0.74               0  South
14       OmicronLtd              0.78              0.76               0   East

In [4]:
# Paired t-Test: Is Model A Better Than Model B?
# Objective
# We want to compare Model A and Model B’s performance using the same clients.

# Hypothesis
# H₀: Mean accuracy of Model A = Model B
# H₁: Mean accuracy is different (two-tailed)

# Importing necessary libraries
from scipy.stats import ttest_rel
# ttest_rel - Paired t-test for related samples
# This test compares the means of two related groups to determine if there is a statistically significant difference between them.

# Paired t-test
t_stat, p_value = ttest_rel(df["Model_A_Accuracy"], df["Model_B_Accuracy"])

print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: 18.33030277982333
p-value: 3.493711229019062e-11

In [5]:
# If p < 0.05, we reject H₀.
if p_value < 0.05:
    print("Reject H₀: There is a significant difference between Model A and Model B.")
else:
    print("Fail to reject H₀: No significant difference between Model A and Model B.")

Reject H₀: There is a significant difference between Model A and Model B.

In [6]:
# If rejected: There's strong evidence that Model A and Model B differ significantly.

In [7]:
# ML Practical Importance
# Model Validation: Confirms if switching models leads to statistically better performance.
# Benchmarking: Avoid decisions based on chance from random test splits.

In [8]:
df.head()  # Display the first few rows of the DataFrame

           Client  Model_A_Accuracy  Model_B_Accuracy  Lead_Converted Region
0       AlphaTech              0.83              0.80               1  North
1        BetaCorp              0.78              0.75               1  South
2  GammaSolutions              0.81              0.79               0   East
3        DeltaInc              0.76              0.74               0   West
4      EpsilonLLC              0.85              0.83               1  North

In [9]:
# Chi-Square Test: Is Region Related to Conversion?
# Objective
# Determine whether Region has a significant impact on Lead_Converted.

# Hypothesis
# H₀: Region and conversion are independent
# H₁: Region and conversion are dependent

# Importing necessary libraries
from scipy.stats import chi2_contingency

# Create a contingency table
contingency_table = pd.crosstab(df["Region"], df["Lead_Converted"])

contingency_table

Lead_Converted  0  1
Region
East            4  0
North           0  4
South           2  2
West            1  2

In [10]:
# Run Chi-square test
chi2, p, dof, expected = chi2_contingency(contingency_table)

print("Chi-square value:", chi2)
print("p-value:", p)

Chi-square value: 8.303571428571429
p-value: 0.04013724715290131

In [11]:
# If p < 0.05, region influences conversion rate.
# Otherwise, region has no impact.
if p < 0.05:
    print("Reject H₀: Region and conversion are dependent.")
else:
    print("Fail to reject H₀: Region and conversion are independent.")

Reject H₀: Region and conversion are dependent.

In [12]:
# ML Practical Importance
# Feature Selection: Remove unimportant categorical variables.
# Customer Segmentation: Identify regions with better conversion for targeted marketing.

In [13]:
# Shapiro-Wilk Test: Is Accuracy Normally Distributed?
# Objective
# Check if Model A’s accuracy is normally distributed to validate assumptions for t-test.

# shapiro-wilk test is a statistical test that checks if a sample comes from a normally distributed population.
from scipy.stats import shapiro

# Test for normality
stat, p = shapiro(df["Model_A_Accuracy"])

# Printing the results of the Shapiro-Wilk test
print("Shapiro-Wilk stat:", stat)
print("p-value:", p)

Shapiro-Wilk stat: 0.9563427567481995
p-value: 0.6291561126708984

In [14]:
# If p > 0.05: Data is normal → You can use parametric tests like t-test
# If p < 0.05: Data is not normal → Use non-parametric tests like Mann-Whitney U test
if p > 0.05:
    print("Data is normally distributed.")
else:
    print("Data is not normally distributed. Consider using non-parametric tests.")
# ML Practical Importance
# Ensures Validity of statistical tests.
# Improves Interpretability when plotting model accuracy distributions.

Data is normally distributed.

In [15]:
# Mann–Whitney U Test (if data is not normal)
# Objective
# Compare two model accuracies without assuming normal distribution.

from scipy.stats import mannwhitneyu

u_stat, p_val = mannwhitneyu(df["Model_A_Accuracy"], df["Model_B_Accuracy"])
print("Mann–Whitney U stat:", u_stat)
print("p-value:", p_val)

# Same as t-test, but robust to outliers and non-normality.

# ML Practical Importance
# Safer when working with small datasets or skewed performance metrics.

Mann–Whitney U stat: 163.0
p-value: 0.03714844547289895

In [16]:
# Kolmogorov-Smirnov (KS) Test
# Objective
# Compare distribution of model predictions to detect shift or drift.
# (We use accuracy here as proxy since we don’t have probability predictions.)

from scipy.stats import ks_2samp

ks_stat, ks_pval = ks_2samp(df["Model_A_Accuracy"], df["Model_B_Accuracy"])
print("KS statistic:", ks_stat)
print("p-value:", ks_pval)

KS statistic: 0.3333333333333333
p-value: 0.3855465198257425

In [17]:
# If p < 0.05: Distributions differ → possible drift or performance shift.
# If p > 0.05: Models behave similarly.
if ks_pval < 0.05:
    print("Reject H₀: Model A and Model B have different distributions.")
else:
    print("Fail to reject H₀: Model A and Model B have similar distributions.")

# ML Practical Importance
# Used for data drift detection, especially in real-time ML pipelines.

Fail to reject H₀: Model A and Model B have similar distributions.

| Test Name      | Used For                         | ML Relevance                            |
| -------------- | -------------------------------- | --------------------------------------- |
| t-Test         | Compare model means              | A/B testing, performance validation     |
| Chi-Square     | Test feature-target independence | Feature selection                       |
| Shapiro-Wilk   | Normality test                   | Validates use of parametric tests       |
| Mann-Whitney U | Non-parametric model comparison  | Robust model evaluation                 |
| KS Test        | Distribution comparison          | Drift detection, model shift monitoring |

# Happy Learning